### ISSUE TITLE
view separate pages for non-logged-in users

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#101]
### Resource

WemX Pro

### Describe the solution you'd like

If you create a separate page (in my example in the footer) then the page is only displayed when the user is logged in. Here a button with true/false would be great, where you can decide if the page is visible for all or only logged in users. 

Background for this is that I must specify an imprint according to the law of my country and this is then not seen.

**Comment by LeanoJ** [comment]
![image](https://github.com/VertisanPRO/pterodactyl/assets/123408114/ccd2cad8-5d80-4d66-9f69-f6cd3f0380f2)
it has probably not worked completely. even with new pages it is not yet displayed to guests.

**Comment by Mubeen142** [comment]
@LeanoJ Enable debug mode, you are getting an error 500

**Comment by LeanoJ** [comment]
its because the "Require Address Information" in settings

**Comment by PadowYT2** [comment]
This has been added in v1.4.0
