### ISSUE TITLE
Slider for player Slots

### ISSUE THREAD

**Issue by SamuelBrownSE** [VertisanPRO/pterodactyl#102]
### Resource

WemX Pro

### Describe the solution you'd like

Is it possible to incorporate a slider into a package, allowing for a range of 1 to 100 player slots, with the price adjusting dynamically based on the selected number of slots and then apply the selected player slot to the server (so it can't be changed)

### Describe alternatives you've considered

You could do like 10 - 15 - 20 - 25 slot and the slider could select from those selected ranges and could display a predetermined price? 

### Additional context

This is similar to features on TC admin portal, its super useful and customers like the freedom of selecting their own play slots

**Comment by PadowYT2** [comment]
Could be easier done, if the input must be a number, make it a slider and you could pick min, max and how many times will it divide
