### ISSUE TITLE
"Send user email" button not working

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#103]
### Resource

WemX Pro

### Describe the issue

By going to Admin area > client management > orders > create there's a setting on the bottom of the page called "send user email", i believe you're supposed to be able to toggle it on and off but as of right not its not possible, instead it toggles the option above it called "Create an instance of package service". I know this is a small bug but should probably get it fixed in next update.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/b4abd661-b563-4d92-8299-ee3be14be508)

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the upcoming update.
