### ISSUE TITLE
Make UI more mobile friendly

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#105]
### Resource

WemX Pro

### Describe the solution you'd like

Currently the UI looks great on desktop but not so good on mobile, text gets cut out, things dont align correctly, and just little things that dont look right. Of course its easier said than done, also considering the software is in its beta phase it looks fine for now but should be improved in the future.

**Comment by PadowYT2** [comment]
Need more information, as where is the text get cut off

**Comment by Shockingg** [comment]
Here let me show some examples:

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/c7b44d70-f4a2-4502-b39d-9c2ee6a42a38)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/23b569c4-4035-429f-a0c0-0df795654d12)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/e159b5df-7c09-47b4-91f6-eb22334a1d96)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/1522f13f-62eb-4cad-b071-924582a66a85)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/af525f0f-767e-4ebf-b53e-932bf56763aa)

**Comment by SamuelBrownSE** [comment]
Have the same issue with mine, its the CSS not setting a width for mobile I'm guessing.

**Comment by Mubeen142** [comment]
Thanks for reporting the issue. I was not able to reproduce all the bugs. Screenshots #2 and #6 have been fixed.

The fixes will be available in the next update. If the other issues still happen in the new update and you are sure its a bug, you can open a new issue.
