### ISSUE TITLE
Big E-Mail Problem

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#107]
### Resource

WemX Pro

### Describe the issue

For example, if you send a user an email for password reset or add an order so that he gets some email, it will not be sent until you go into email and send a test mail, all emails will be sent.

### Pterodactyl Panel Version

x

### Resource Version

1.1.0

### To Reproduce

1. Send a Password reset to a User or Create a order for him
2. Look in the email --> History the email dosnt send
3.  go to email --> configure and send a test mail
4.  go to email --> hostory and the maail (all not sendet mails) was send

### Expected Behaviour

That the email is not sent only when testing

### Screenshots

do not approve

### Additional Information

-do not approve

**Comment by Mubeen142** [comment]
This is not a bug. You have not setup cron, https://docs.wemx.net/en/installation#setup-cron
