### ISSUE TITLE
Unable to Activate an Custom Admin Theme

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#108]
### Resource

WemX Pro

### Describe the issue

In the admin panel, trying to activate a custom theme for the admin panel does not work or give any error. 

### Pterodactyl Panel Version

N/A

### Resource Version

N/A

### To Reproduce

1. Duplicate the "default files" for the admin theme.
2. Change/edit the theme.php to match the name folder.
3. Go to the admin panel -> Admin Themes -> try activating your custom admin theme. 

### Expected Behaviour

Should successfully change like the client theme.

### Additional Information

Client Changing Themes work correctly by actually saying "successfully activate" and your theme you activated says active.

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the next update.
