### ISSUE TITLE
WemX Portal Theme has re-appeared.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#109]
### Resource

WemX Pro

### Describe the issue

The WemX Portal Theme was not supposed to be in the portal itself.

### Pterodactyl Panel Version

N/A

### Resource Version

N/A

### To Reproduce

1. Head to domain.com/admin/settings/portal 
2. You can see the WemX Portal is there (where it shouldn't be there)

### Expected Behaviour

Only Default Portal Page is there.

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/39040261/9080f227-e637-4c52-9ea8-8945eac3e27b)

### Additional Information

Mubeen says its not suppose to be there unless that has changed.

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the next update
