### ISSUE TITLE
Change MB to GB (or let us write it ourself)

### ISSUE THREAD

**Issue by Davidbp99** [VertisanPRO/pterodactyl#11]
### Resource

Billing

### Is your feature request related to a problem? Please describe

So I did some testing with the panel to some server owners. When they looked fast at the billing place. They thought 2000MB was 200MB. As normally most companies starts using 2GB, 2.5GB etc when they are at those numbers. Not MB.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/40523727/179716891-a84c883a-80f9-4257-88d7-8109257e1aa8.png)
Use pterodactyl own way of rounding the numbers when doing it. So nothing gets off by a number somewhere.

Would like to see an option to select MB, GB or TB and so on when doing the packages. So if we write 2 and select GB. Then it will write the numbers it need for 2GB into MB (as pterodactyl is MB based). Then display GB instead of MB when someone would buy a package.

This should work for ram and storage on the packages.

**Comment by carpangling** [comment]
This would be a ice addition
