### ISSUE TITLE
Buying balance with balance

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#110]
### Resource

WemX Pro

### Describe the issue

Currently you can actually buy account balance with your current account balance, which is a little odd but I think it would probably be better to remove this lol as its completely useless.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

### To Reproduce

1. Login to client account
2. Click add balance
3. Select amount
4. Choose to pay with account balance

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/960106e0-3ca0-43aa-9ca1-c8d678e9d2b9)

**Comment by Mubeen142** [comment]
@Shockingg This issue can be fixed by deleting the "Balance" gateway from admin area, then create it again with just display name "Balance". 

The bug has been fixed for in the future even if the display name is something else than "Balance"
