### ISSUE TITLE
Invoice refunding not working

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#114]
### Resource

WemX Pro

### Describe the issue

I believe the invoice refunding function does not work at the moment, when attempting to refund there is a field to enter a "Transaction ID", I've entered every ID related to the invoice / payment I could find and I still get the error shown in the screenshot. I believe this is a bug but it might be an issue just on my end I'm not sure.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

### To Reproduce

1. Pay an invoice
2. Find the client / user in admin area
3. Go to the invoices tab
4. Click manage on the payed invoice
5. Enter transaction ID and click refund

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/77bd37be-c305-440f-bd38-b0f029a8dec8)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/f496d411-e55c-4f78-839a-304fa69d4270)

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the next update.
