### ISSUE TITLE
Discord button not working

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#116]
### Resource

WemX Pro

### Describe the issue

Once you've linked your discord server in the admin area an icon appears in the footer, this should redirect to the discord server. Instead it either redirects to the dashboard or if you have other socials linked too, for example twitter, the discord icon will just redirect to twitter too. I believe the discord icon is the only one that has this issue, all the others seem to work fine. Just a small bug.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

### To Reproduce

1. Admin area > configuration > theme settings
2. Add discord url
3. Login to client account and click the discord icon in the footer
4. Redirects to dashboard

OR

1. Admin area > configuration > theme settings
2. Add discord url & twitter url
3. Login to client account and click the discord icon in the footer
4. Redirects to twitter page

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the next update.
