### ISSUE TITLE
Using the Verify button

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/pterodactyl#117]
### Resource

WemX Pro

### Describe the issue

When you get an email with a code and click the verify button, you have the code in the URL, but it doesn't get inputted automatically

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

### Screenshots

![https://cdn.padow.ru/D4Njo](https://cdn.padow.ru/D4Njo)

**Comment by VanillaChan6571** [comment]
You also cannot paste the code in directly as it results just inputting 1 number from the clipboard.

**Comment by PadowYT2** [comment]
> You also cannot paste the code in directly as it results just inputting 1 number from the clipboard.

#113

**Comment by Mubeen142** [comment]
Thanks for reporting the issue. You can now click the link and the code will be directly pasted in the next update.
