### ISSUE TITLE
global stock changes incorrectly

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#119]
### Resource

WemX Pro

### Describe the issue

furthermore, the value of the global stock of a location is automatically changed when a server is purchased

### Pterodactyl Panel Version

 1.11.3

### Resource Version

1.1.0

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/123408114/0e2f282d-2454-419f-8578-0bb8123bb45b)

**Comment by Mubeen142** [comment]
Thanks for reporting the bug, I have fixed it for the next update.

The stock will not reduce if the value is set to -1
