### ISSUE TITLE
Automatic Payments

### ISSUE THREAD

**Issue by Davidbp99** [VertisanPRO/pterodactyl#12]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Right now the client needs to go on the panel and pay for the service each month (or how you got it setup). This can be a pain for some. From the client and company side.

### Describe the solution you'd like

Add an way for stripe and paypal where the client can select in the billing to have payments automatic (works on both last time I looked at the API docs they got).

As well give the client the power to go away from automatic payments. <- can be disabled if the company forces automatic payments

As well let the company force automatic payments on services. For something in the billing admin section. As some company only wants automatic payments and some is against it.

If a cancel request comes in from the client the stripe/paypal system should remove the client from the billing cycle.

**Comment by PadowYT2** [comment]
You could just click Renew button to renew double/triple/and so on
