### ISSUE TITLE
Custom Client Theme does not get used despite being set to default/active.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#120]
### Resource

WemX Pro

### Describe the issue

The Tailwind folder still gets used despite the client theme is not set to "Tailwind" which is the default folder.

### Pterodactyl Panel Version

N/A

### Resource Version

1.1.0

### To Reproduce

1. Activate your custom theme as the status should say active.
2. Make changes in the Tailwind folder (not your custom theme folder)
3. Changes were applied but it shouldn't since the theme is not set to tailwind as the status is inactive.

### Expected Behaviour

Tailwind shouldn't be used if active theme is set to non-tailwind folder.

### Additional Information

This may also happen on admin theme too but unable to test it since its broken.

**Comment by Mubeen142** [comment]
Hi @VanillaChan6571 

I could not replicate this I am able to create themes perfectly fine. Please clear view cache and config cache. If you are sure this is a bug please reopen the issue with more information

**Comment by Mubeen142** [comment]
I believe you are right, Gigabait just sent me more info looks like it happens for certain files when they are not correctly using the wrapper. I’ll take a look later today

**Comment by thattheredstoner** [comment]
In some of the files of the default theme, certain php references are hard-coded to the default tailwind folder, what I had to do was use the find tool in VSCode, to find all references of tailwind in my custom theme folder and replace it from "tailwind" to my custom theme name. This solves the issue mentioned

**Comment by GIGABAIT93** [comment]
It is not a mistake to specify in the template direct references to the dependencies it needs, as this will only be used in this template. If you copy the template and then edit it, you need to take this into account. Moreover, if you specify static links to dependencies, it will be more optimized for loading pages

**Comment by thattheredstoner** [comment]
I understand, but I believe this should be mentioned within the custom theme documentation on the website, in case people do not check the files, many thanks.

**Comment by Mubeen142** [comment]
@VanillaChan6571 Does this bug still happen or was it fixed?

**Comment by Mubeen142** [comment]
I am going to close this ticket assuming it was fixed in a previous update, please reopen the ticket if you believe that is not the case

**Comment by VanillaChan6571** [comment]
@Mubeen142 there are some certain files like the registration/password reset pages are still hard coded to use wemx favicon/title.

**Comment by VanillaChan6571** [comment]
![image](https://github.com/VertisanPRO/pterodactyl/assets/39040261/40446b4a-d921-4c50-b16a-98597de05264)

**Comment by VanillaChan6571** [comment]
This wemx Icon is still hard coded.

**Comment by Mubeen142** [comment]
Thank you @VanillaChan6571 for reporting this issue, its been fixed.
