### ISSUE TITLE
Text bug in the admin page with active maintenance

### ISSUE THREAD

**Issue by Mr-sl1d3r** [VertisanPRO/pterodactyl#122]
### Resource

WemX Pro

### Describe the issue

![image](https://github.com/VertisanPRO/pterodactyl/assets/76396365/14465106-252c-4e78-b0a0-80d48cb77eca)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

**Comment by Mubeen142** [comment]
Thank you for reporting the issue, we've fixed it for next update :)
