### ISSUE TITLE
Contact Page Bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#123]
### Resource

WemX Pro

### Describe the issue

In the portal when you click "Contact" on the header it takes you to the contact us page, but for some reason the logged in header shows on this page despite the user not being logged in, they cant access the pages but they appear nevertheless. Im terrible at explaining but you should see what I mean in the screenshots.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

### To Reproduce

1. Make sure you're not logged in
2. Visit portal page
3. Click "Contact"
4. See the header at the top of the page

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/ca971c0f-f31d-432d-a71b-6beac714a165)

**Comment by Mubeen142** [comment]
Hi @Shockingg 

I do not believe this to be a bug. Guests can still view the contact us page and a lot of other pages. If they want to visit a user specific page they are prompted to login

**Comment by ShockYT** [comment]
Oh right okay no worries, just looked like a bug at first.
