### ISSUE TITLE
Strange titles on Services page

### ISSUE THREAD

**Issue by part1cleth1ef** [VertisanPRO/pterodactyl#127]
### Resource

WemX Pro

### Describe the issue

There are strange titles on the Services Page

### Pterodactyl Panel Version

N/A

### Resource Version

1.2.0

### Expected Behaviour

It doesn't look tidy... that's it.

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/70655838/22da91c0-38b6-42a1-a9f9-399f36e78b8e)

**Comment by PadowYT2** [comment]
What's wrong exactly?

**Comment by Mubeen142** [comment]
@part1cleth1ef What's wrong with the titles? I don't see any issue here apart from the spacing between $ and 2

**Comment by thattheredstoner** [comment]
I believe what they meant was the price being misaligned between the price cards, but that's partially a user error (2 line descriptions/subtitles)

**Comment by PadowYT2** [comment]
Closing as no response has been made
