### ISSUE TITLE
Problems installing SteamCMD after buying from WemX

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#128]
### Resource

WemX Pro

### Describe the issue

I think I found a problem, if you try to create different SteamCMD servers you need most up to two extra ports but they are not automatically created or added so you have to do that at pterodactyl extra
and if you create a SteamCMD server that needs a Steam Auth token you can't save it at wemx and i can't just write my own token in there and if you take that as checkout variable it still won't work 
In my case I have taken the SteamCMD Sertver for Euro truck SIm 2

### Pterodactyl Panel Version

1.2.0

### Resource Version

1.2.0

### Expected Behaviour

That one e.g. you ports with the Instalation of the PSiele immediately added and not extra into the Ptero panel must and that the Steam Auto Token is queried with the Checkout and one can make nevertheless changes at the package attitudes.

**Comment by PadowYT2** [comment]
1. 1.2.0 Pterodactyl Version is really old
2. About ports not getting automatically used - #98
