### ISSUE TITLE
Auto allocation bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#129]
### Resource

WemX Pro

### Describe the issue

With the current pterodactyl version there is a setting to allow auto allocation of ports, but when this setting is enabled and a user creates an order, it throws an error stating that there are no allocations available, when it should create the server along with the allocations. Please get this fixed in next update if possible.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

**Comment by Mubeen142** [comment]
@Shockingg the allocation setting in pterodactyl is for allocation created by users on pterodactyl not for new servers. To confirm, contact pterodactyl and ask them about it. its not for creating auto allocations for new servers
