### ISSUE TITLE
Redirecting to /portal when trying to use the API

### ISSUE THREAD

**Issue by JackBailey** [VertisanPRO/pterodactyl#13]
### Resource

Billing

### Describe the issue

I'm trying to use the API to easily restart a bot via discord command if a server crashes or just stops working so that staff can easily restart it without having to have access to the server itself.

Using the same request I used before installing the billing addon:
`curl -X POST https://example.com/api/client/servers/123456/power -d '{"signal":"restart"}' -H '{"Authorization":"Bearer XXXXXXXXXXX"}'`

Results in the page being redirected to /portal:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='https://example.com/portal'" />

        <title>Redirecting to https://example.com/portal</title>
    </head>
    <body>
        Redirecting to <a href="https://example.com/portal">https://example.com/portal</a>.
    </body>
</html>
```

### Pterodactyl Panel Version

1.9.2

### Resource Version

2.6.0

### To Reproduce

1. Install plugin
2. Try to access any of the api without being logged in (although using API key)

### Expected Behaviour

Allow access to the API without being redirected

**Comment by Jack-Bailey** [comment]
I believe this also might effect a schedule of restarting the server although thats purely from speculation because it worked perfectly before installing the billing system and now fails

**Comment by PadowYT2** [comment]
Found the problem
`app/Http/Controllers/Base/IndexController.php` (lines 33-40)
```php
if (Auth::guest()){
    if (config('billing.portal') == "true") {
        return redirect('/portal');
    } else {
        return redirect('/auth/login');
    }
}
```

Removing it makes it worse btw

**Comment by Mubeen142** [comment]
Hi,

Thanks for the report. This is a pretty serious issue. I will try to solve it asap

**Comment by PadowYT2** [comment]
Was fixed for schedules, but it still redirects to `/portal`, is this intended?
