### ISSUE TITLE
Subscription Period Bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#130]
### Resource

WemX Pro

### Describe the issue

Looks like there's something wrong with the weekly, monthly, quarterly periods not displaying correctly. See screenshots for better context.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/6faa1387-1c03-4b74-969c-1f4ae2350b63)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/36fdd9ba-ab22-4dbc-b609-2e37c6a2d277)

**Comment by Mubeen142** [comment]
Thanks for reporting the issue. The keys weren't added to the language files, it should be fixed in the next update.
