### ISSUE TITLE
1.2.0 Fresh Install or Fresh Database cannot be installed.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#131]
### Resource

WemX Pro

### Describe the issue

When following the install guide for 1.2.0 it seems during php artisan, it attempts to try to connect to a null database with a null username which is a result of 

### **_SQLSTATE[HY000] [1698] Access denied for user ''@'localhost' (SQL: select `value`, `key` from `settings`)_**                                                            

If you manually edit the .env file and add your database credentials you will just get an error of  
### **_Base table or view not found: 1146 Table 'wemx.settings' doesn't exist (SQL: select `value`, `key` from `settings`)_**

# Bypass/Fix Method:
In file `app/Providers/AppServiceProvider.php` on line 45 comment out the code to look like this:

### // Theme::registerComponents();

This should work and now you can run `php artisan migrate --force`

Thanks to Mubeen for finding the bypass/fix for this for now until 1.3.0?

### Pterodactyl Panel Version

N/A

### Resource Version

1.2.0

### To Reproduce

Follow the install guide on a new VPS or Install to get the issue

### Expected Behaviour

N/A

### Screenshots

N/A

### Additional Information

Download to replace if needed:
[AppServiceProvider.php.txt](https://github.com/VertisanPRO/pterodactyl/files/12062230/AppServiceProvider.php.txt)

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, was fixed for the next update.
