### ISSUE TITLE
email-history

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#137]
### Resource

WemX Pro

### Describe the issue

I think I found a bug?

Wanted to share that even after viewing the notificationn the icon still flashes. Now I have found / had the error in addition.

### Pterodactyl Panel Version

 1.11.3

### Resource Version

1.2.0

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/123408114/5720bb69-2c62-4d9c-a229-60e10484ee1a)
![image](https://github.com/VertisanPRO/pterodactyl/assets/123408114/4617212b-b598-4d80-b20a-023ab593e824)

**Comment by PadowYT2** [comment]
Isn't a bug, permissions set falsely, get help on our Discord Server
