### ISSUE TITLE
Ability for customer to select game versions

### ISSUE THREAD

**Issue by SamuelBrownSE** [VertisanPRO/pterodactyl#138]
### Resource

WemX Pro

### Describe the solution you'd like

Can you implement something on the game selection for a version selection, e.g. with Minecraft if they want paper or vanilla etc? 

### Describe alternatives you've considered

I'm sure there is a addon for the pterodactyl panel for this but would make sense to do it at purchase.

**Comment by PadowYT2** [comment]
On what purchase?

**Comment by PadowYT2** [comment]
@SamuelBrownSE ^

**Comment by SamuelBrownSE** [comment]
NVM ive done it 
![image](https://github.com/VertisanPRO/pterodactyl/assets/123277579/253b1230-15c5-4211-8ed8-7bad9e2fe266)
