### ISSUE TITLE
Backup via Googledrive or Mega.Io

### ISSUE THREAD

**Issue by vynxcc** [VertisanPRO/pterodactyl#14]
### Resource

Plugins

### Is your feature request related to a problem? Please describe

Automatic backups via Google drive/online storage backup for servers.

### Describe the solution you'd like

A page to setup automatic server backups uploaded to Google drive.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by PadowYT2** [comment]
Not here

**Comment by PadowYT2** [comment]
And Plugins has nothing to do with Backups
