### ISSUE TITLE
Configuration System

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#140]
### Resource

WemX Pro

### Describe the solution you'd like

Would love to see a feature where if you enable it for a package users can customize how much ram, cpu threads, storage etc for their server. Something similar to WHMCS's custom server configuration system.

**Comment by Mubeen142** [comment]
@Shockingg As far as I am concerned, WHMCS does not have any configurable options for RAM, memory etc

**Comment by PadowYT2** [comment]
> @Shockingg As far as I am concerned, WHMCS does not have any configurable options for RAM, memory etc

It does, an example is at [PebbleHost](https://pebblehost.com/)

**Comment by Shockingg** [comment]
Yea it does, another example is [Wyvern](https://wyvern.host/)

**Comment by Mubeen142** [comment]
The Pterodactyl module for WHMCS does not have support for configurable options. Pebblehost does not use Pterodactyl and is likely a custom module same with [Wyvern](https://wyvern.host/) which is wisp.

**Comment by PadowYT2** [comment]
> The Pterodactyl module for WHMCS does not have support for configurable options. Pebblehost does not use Pterodactyl and is likely a custom module same with [Wyvern](https://wyvern.host/) which is wisp.

Well, we could just when creating a server, on the page you have the cuztomization and just create the server with user's pick

**Comment by Shockingg** [comment]
Yea I don't see why this isn't possible, the pterodactyl API fully supports it I believe?

**Comment by GTASwunk** [comment]
> The Pterodactyl module for WHMCS does not have support for configurable options. Pebblehost does not use Pterodactyl and is likely a custom module same with [Wyvern](https://wyvern.host/) which is wisp.

Actually, WHMCS has something called "Configurational Options" and if you do it correctly, you can use it to set custom amounts.

![Screenshot 2023-07-17 142744](https://github.com/VertisanPRO/pterodactyl/assets/103612421/1635ac9f-2cb7-4698-94db-315053c53a5f)

**Comment by PadowYT2** [comment]
This issue has been merged into #238
