### ISSUE TITLE
Visual Issue with Line Break in Badge

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#141]
### Resource

WemX Pro

### Describe the issue

There is a visual issue with the line break in the price badge section of the code. Currently, the badge is displayed with a line break that causes the badge text to appear distorted or misplaced. This issue occurs when the price badge has a long text that exceeds the available width.

View the price badge section containing the following code:

@isset($price->data['badge'])
    <span class="bg-primary-100 text-primary-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-primary-900 dark:text-primary-300">
        {{ $price->data['badge'] }}
    </span>
@endisset

Expected Result:
The price badge should display the badge text within a single line without any visual distortion.

Actual Result:
The price badge text is displayed with a line break when the content is too long, causing visual issues with the badge alignment.

Proposed Solution:
To address this issue, we suggest implementing a "nobr" (no line break) tag around the price badge to prevent line breaks within the badge text. The updated code should look like the following:

@isset($price->data['badge'])
    <nobr>
        <span class="bg-primary-100 text-primary-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-primary-900 dark:text-primary-300">
            {{ $price->data['badge'] }}
        </span>
    </nobr>
@endisset

By using the "nobr" tag, the price badge text will be displayed on a single line, ensuring a consistent and visually appealing presentation.

### Pterodactyl Panel Version

 1.11.3

### Resource Version

1.3.0

### To Reproduce

screenshot

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/123408114/19548e5c-3aa1-42d1-8eaa-c735142a64c4)

### Additional Information

/var/www/wemx/resources/themes/client/tailwind/store/packages/view.blade.php

**Comment by Mubeen142** [comment]
Thank you for reporting the issue @LeanoJ it has been fixed for next update.
