### ISSUE TITLE
package pictures display

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#142]
### Resource

WemX Pro

### Describe the solution you'd like

Since you can add images to packages anyway, I thought I could share a feature here what I have simply implemented with me here, because it might be interesting for one or the other. With a line you could directly integrate the icon also. This makes visually already a lot. See pictures.

In the portal as well as in the client area I have set.
It is only this line:
<img class="m-7 h-auto" src="{{ asset('storage/products/' . $package->icon) }}" alt=""/>

![2023-07-19_07h48_59](https://github.com/VertisanPRO/pterodactyl/assets/123408114/64069d3e-f300-4879-a3da-c65c4c82efb9)
![2023-07-19_07h49_13](https://cdn.padow.ru/B0uQ8)
![2023-07-19_07h49_22](https://cdn.padow.ru/hYHF9)
![2023-07-19_07h49_46](https://github.com/VertisanPRO/pterodactyl/assets/123408114/62045748-b612-4aef-bcd9-514c56677a90)

**Comment by LeanoJ** [comment]
<div class="flex justify-center items-center">
        <img class="py-2 max-w-full max-h-[13rem] h-auto" src="{{ asset('storage/products/' . $package->icon) }}" alt=""/>
</div>

I think a size adjustment would be a little better

**Comment by LeanoJ** [comment]
<img class="py-2 max-w-full max-h-[13rem] h-auto" src="{{ asset('storage/products/' . $package->icon) }}" alt=""/>


I think a size adjustment would be a little better

**Comment by PadowYT2** [comment]
This has been added in v1.4.0
