### ISSUE TITLE
Permission Groups (Full permission)

### ISSUE THREAD

**Issue by Noah-huisman** [VertisanPRO/pterodactyl#144]
### Resource

WemX Pro

### Describe the solution you'd like

I would like to see the following feature within the next update.

When giving permissions to a group, currently you have to click each box one by one. And this is not doable with the amount of permissions. 

Is there a possibility of adding a "Select All" function, or a "Full permissions" function?

![Screenshot 2023-07-20 172902](https://github.com/VertisanPRO/pterodactyl/assets/102486543/ce2a5255-77b0-42f3-9f11-add263273cf3)

**Comment by PadowYT2** [comment]
You would just need to toggle these 2 permissions:
![https://cdn.padow.ru/He4kd](https://cdn.padow.ru/He4kd)
