### ISSUE TITLE
Preview Email Bug (Stuck on page)

### ISSUE THREAD

**Issue by Noah-huisman** [VertisanPRO/pterodactyl#145]
### Resource

WemX Pro

### Describe the issue

If you click on the user, then go to Emails.

And then click on "Preview" the whole page darkens and you can no longer click "Close". (So your stuck on that page until refresh)

![Screenshot 2023-07-20 173559](https://github.com/VertisanPRO/pterodactyl/assets/102486543/48cee826-aafc-46b9-9138-ae92ab1b38f6)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0 (Newest)

### To Reproduce

Go to Users, Emails, Preview

### Expected Behaviour

That the "Close" button does work

### Screenshots

![Screenshot 2023-07-20 173913](https://github.com/VertisanPRO/pterodactyl/assets/102486543/3ed7e4c9-2f6d-47fe-aed3-665a5b372e8a)

**Comment by PadowYT2** [comment]
This has been fixed in v1.4.0
