### ISSUE TITLE
Specific User order glitch

### ISSUE THREAD

**Issue by Noah-huisman** [VertisanPRO/pterodactyl#146]
### Resource

WemX Pro

### Describe the issue

With the user (In this case, someone with ID 3), if I click on "Orders" where normally the orders of user 3 should come. only the orders of user 1 ID come up.

![Screenshot 2023-07-20 194636](https://github.com/VertisanPRO/pterodactyl/assets/102486543/08755779-525e-4c7d-9ec7-437d09a11656)
![Screenshot 2023-07-20 194541](https://github.com/VertisanPRO/pterodactyl/assets/102486543/871d2c5e-ac7a-4869-9ab3-84bbdf693eb7)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0 (Newest)

### To Reproduce

User, Orders,

### Expected Behaviour

To show the orders of the correct user.

**Comment by GIGABAIT93** [comment]
Fixed in version 1.4.0
