### ISSUE TITLE
Buy products with Balance

### ISSUE THREAD

**Issue by Noah-huisman** [VertisanPRO/pterodactyl#147]
### Resource

WemX Pro

### Describe the solution you'd like

I would like to see a feature that makes it possible to buy a product with the user's balance.

### Additional context

![Screenshot 2023-07-20 203423](https://github.com/VertisanPRO/pterodactyl/assets/102486543/b100c5c8-6f73-4d56-b172-ee13bb38dffa)
![Screenshot 2023-07-20 203405](https://github.com/VertisanPRO/pterodactyl/assets/102486543/bd4bdd07-5db7-4c5b-9e4f-95b071259a20)

**Comment by PadowYT2** [comment]
You would need add "Balance" as the payment gateway
