### ISSUE TITLE
Admin Manually Creates an order, the order does not respect the chosen server locations or OOM Killer of the package values.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#148]
### Resource

WemX Pro

### Describe the issue

When an admin manually creates an order for a "affiliate user" the server gets created on any server location and not what the package it set.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.3.0

### To Reproduce

1. Create a new order.
2. Select the package and hit create.
3. The server will install on the location thats not respected via package.

### Expected Behaviour

Order through the packages values.

### Additional Information

I have 2 locations that is for clients/customers. I cannot have admin create order not respecting the values due to some servers I linked are for testing/not for public. So I am not sure why the package was created on my test server. I think its because the test game server is ID 1 so the admin order will always create on ID 1 which shouldn't happen and respect the packages location that can be created on.

**Comment by GIGABAIT93** [comment]
Fixed in version 1.4.0
