### ISSUE TITLE
When deleting existing page redirect to coupons

### ISSUE THREAD

**Issue by Noah-huisman** [VertisanPRO/pterodactyl#153]
### Resource

WemX Pro

### Describe the issue

If I delete an existing page in domain.com/admin/pages. I am redirected to domain.com/admin/coupons and get the message there that the page has been successfully deleted

**on domain.com/admin/pages**
![Screenshot 2023-07-21 212235](https://github.com/VertisanPRO/pterodactyl/assets/102486543/10450bbd-9c30-4a47-b300-734402975ee7)

**on domain.com/admin/coupons**
![Screenshot 2023-07-21 212250](https://github.com/VertisanPRO/pterodactyl/assets/102486543/4bee860d-796c-47e3-82f3-aa85f05aa830)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0 (Newest)

### To Reproduce

Go to domain.com/admin/pages and delete a page.

### Expected Behaviour

That the notification is displayed within domain.com/admin/pages

**Comment by GIGABAIT93** [comment]
Will be fixed in upcoming update 1.5.0
