### ISSUE TITLE
Letting customers choose their preferred server software 

### ISSUE THREAD

**Issue by DartNodes** [VertisanPRO/pterodactyl#155]
### Resource

WemX Pro

### Describe the solution you'd like

Add a feature that lets customers choose their preferred server software instead of just setting a default software. Something like the screenshot 
![Screenshot at 2023-07-22 20-40-24](https://github.com/VertisanPRO/pterodactyl/assets/139348516/d1567558-3ac9-4fa4-9dc2-f1a57caf8fc6)

**Comment by VanillaChan6571** [comment]
This would solve part issue with customers wanting a server that’s not default software, this doesn’t solve the issue if the server is already created and they want to switch for example paper -> forge, the start up commands would be completely different.

**Comment by Mubeen142** [comment]
Hi,

Thanks for your suggesting, however I have to agree with @VanillaChan6571 on this one. The suggested changes have more of the characteristics of a Pterodactyl addon than they do with WemX Pro. 

WemX Pro is meant to be billing software, I would suggest looking for an addon.
