### ISSUE TITLE
Incorrect Server Status Display after Cancellation

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#158]
### Resource

WemX Pro

### Describe the issue

When I cancel a server that is marked as "Suspended" and listed as "inactive," it is properly canceled. However, if I click on "do not cancel" afterwards, the server is moved to the active servers list, which is incorrect. Despite this, the server remains unavailable, as expected. The issue only lies in the incorrect status display.

### Pterodactyl Panel Version

 1.11.3

### Resource Version

1.3.0 - maybe dev

**Comment by Mubeen142** [comment]
Thanks for reporting this bug @LeanoJ 

I have added a method that checks if the order status is not active, you won't be able to cancel it.
