### ISSUE TITLE
Wrong Displey

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#159]
### Resource

WemX Pro

### Describe the issue

If you edit a user so go here https://hosting.example.com/admin/users/{id}/edit and then go to orders there are not the user orders but the orders of the admin account with which you edit the user / anschauenz

### Pterodactyl Panel Version

latest

### Resource Version

latest

### To Reproduce

1. go to Admin Area
2. got o Customers --> Clients
3. click on any user on edit
4. press orders and now you can see the orders of the admin account with which you are currently viewing the user

**Comment by PadowYT2** [comment]
`latest` isn't a version
