### ISSUE TITLE
Wrong Displey

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#161]
### Resource

WemX Pro

### Describe the issue

If you edit a user so go here [https://hosting.example.com/admin/users/{id}/edit](https://hosting.example.com/admin/users/%7Bid%7D/edit) and then go to orders there are not the user orders but the orders of the admin account with which you edit the user / anschauenz

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.3.0

### To Reproduce

1. go to Admin Area
2. got o Customers --> Clients
3. click on any user on edit
4. press orders and now you can see the orders of the admin account with which you are currently viewing the user

**Comment by GIGABAIT93** [comment]
fixed in version 1.4.0

**Comment by Partymann2000** [comment]
This bug still exists
