### ISSUE TITLE
Renewal Bugs

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#168]
### Resource

WemX Pro

### Describe the issue

There seems to be a translation issue when a service is suspended it shows "client.suspended", not only that but when you click the yellow renew button on a suspended service as seen in the screenshot it just does nothing, same thing goes with the green renew button, it makes an invoice, user pays invoice, but nothing happens except user loses funds. Needs to be fixed next update for sure.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.3.0

### To Reproduce

1. Suspend service or wait
2. Try renew
3. See renew buttons dont work, and client.suspended

**Comment by GIGABAIT93** [comment]
You can check it in the new version?

**Comment by Mubeen142** [comment]
This issue was fixed in a previous update
