### ISSUE TITLE
Incorrect date

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#171]
### Resource

WemX Pro

### Describe the issue

Seems to be a bug on the invoices page, where it shows the date at which the invoice was payed always seems to be incorrect. Screenshot for more context. I'm not sure if this also happens on unpaid invoices, but it might. 

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. Buy a new service
2. Dashboard > Service > Manage
3. Click invoices
4. See incorrect date

### Expected Behaviour

Show the correct date at which the incoice was payed.

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/835303f5-99ab-4f37-87da-f38ee08b1084)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/fea8fccf-24b3-4d2c-9989-f34d9d442955)
![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/4cf03d87-e549-401f-8b3e-eee67e815daf)

**Comment by Mubeen142** [comment]
Hey @Shockingg 

Thank you for reporting this bug, I have fixed the issue for next update :)

The system was showing the user created at date rather than payment date.
