### ISSUE TITLE
Subscriptions missing

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#173]
### Resource

WemX Pro

### Describe the issue

since the last update there is nothing to see at /subscriptions although a user has a subscription

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

since the last update there is nothing to see at /subscriptions although a user has a subscription

**Comment by VanillaChan6571** [comment]
Not really a bug, since most of your subscriptions/packages are in the user's dashboard.

More less it should really be marked as "what is this for?"

**Comment by Partymann2000** [comment]
since the last update, subs are no longer displayed for the user

**Comment by Mubeen142** [comment]
Hey @Partymann2000 

I believe this bug was already fixed in a previous update. If you think that is false, please reopen the issue with exact steps to reproduce the issue
