### ISSUE TITLE
Admin-User-Edit

### ISSUE THREAD

**Issue by ShadowPro1** [VertisanPRO/pterodactyl#174]
### Resource

WemX Pro

### Describe the issue

if u try to delete the device list of that user it dosen't do anyting.

### Pterodactyl Panel Version

1.11.3

### Resource Version

v1.4.0

### To Reproduce

1. go to admin/users/(id)edit
2. try to delete the device list of that user

### Expected Behaviour

It should remove it but it dosen't do anyting

**Comment by Mubeen142** [comment]
Thank you for reporting this bug @ShadowPro1 the bug has been fixed for next update.
