### ISSUE TITLE
Date Updated bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#177]
### Resource

WemX Pro

### Describe the issue

Seems to be a bug with the "Date Updated: " element on custom pages. It does not display the correct date of when the page was edited. 

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. Edit a custom page
2. Check the date

### Expected Behaviour

Display the date at which the document was last updated.

### Screenshots

I updated the following page today (10'th of August), and here is the date it displays:

<img width="273" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/137300798/f4596e7c-2822-4ad8-87a6-21a9d1d20b9c">

**Comment by VanillaChan6571** [comment]
This is **NOT** a bug as this is an error on user for not setting the time or date correctly on the machine system. You will need to fix this yourself.
