### ISSUE TITLE
store , 2 5 10 year plans

### ISSUE THREAD

**Issue by ShadowPro1** [VertisanPRO/pterodactyl#178]
### Resource

WemX Pro

### Describe the issue

Its not displaying the years after the yearly plan
![image](https://github.com/VertisanPRO/pterodactyl/assets/86128177/00076d3f-ba26-4ace-b9f7-de3aa3076c31)

### Pterodactyl Panel Version

1.11.3

### Resource Version

v1.4.0

### To Reproduce

Go to https://xxx/admin/packages
make a package add the price and seee

### Expected Behaviour

It should display the years

**Comment by Mubeen142** [comment]
Hi @ShadowPro1 

Thank you for reporting the issue, it has been fixed for next update.
