### ISSUE TITLE
Custom Notes Not Working

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#179]
### Resource

WemX Pro

### Describe the issue

As far as I can tell, the custom notes feature during checkout does nothing at all and does not work as intended. The notes are not visible from the admin panel whatsoever.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. Place an order
2. Include additional notes
3. Not visible anywhere

### Expected Behaviour

I believe the notes should appear when managing the order in the admin panel.

### Screenshots

<img width="822" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/137300798/25200c65-06ea-4f41-9aa9-99e53e6415e0">

**Comment by VanillaChan6571** [comment]
I believe they are visible in the database. Maybe.

**Comment by Mubeen142** [comment]
Thanks for reporting the issue @Shockingg it has been fixed for next update. I also included a feature in package settings to enable / disable notes
