### ISSUE TITLE
Improved liscence key system

### ISSUE THREAD

**Issue by starrider346** [VertisanPRO/pterodactyl#182]
### Resource

WemX Pro

### Describe the solution you'd like

Make it so if a liscence expires, keep it active for a day or 2 before shutting it off with a warning as my site has been offline for over a day while I wait for Mubeen to resolve the broken renewals. 

### Describe alternatives you've considered

Fix broken renewals.

**Comment by ShadowPro1** [comment]
Also renew buton is broken on wemx

**Comment by PadowYT2** [comment]
This is a wrong place to report these kind of stuff
