### ISSUE TITLE
Default currency symbol instead of own

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#183]
### Resource

WemX Pro

### Describe the issue

Instead of the selected symbol e.g. € you will see the default symbol $

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. go to https://xxx.com/dashboard
2. select a aktive plan
3. click extend
4. and now you can see not the selectet currency symbol
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/757aff2c-2a6c-48a5-b603-4bfcb0904574)

### Expected Behaviour

That my own selected currency symbol is displayed

**Comment by Mubeen142** [comment]
Thank you for reporting the bug, we've fixed it for next update!
