### ISSUE TITLE
Stripe issue

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#185]
### Resource

WemX Pro

### Describe the issue

Currently when a user attempts to renew their service via stripe checkout, and they make a successful payment for some reason the invoice does not get marked as paid automatically, that with the fact that there's also a bug that doesnt let admins mark the invoice as paid either. This is a big bug that needs fixing asap (next update).

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.4.0

### To Reproduce

1. On an active service click "renew"
2. Create an invoice
3. Attempt to pay the invoice via stripe checkout
4. See how the invoice does not get marked as paid and the date is not extended despite the user being charged successfully.

### Expected Behaviour

1. Invoice gets marked as paid and the renewal date is extended.

**Comment by Mubeen142** [comment]
@Shockingg I have fixed the issue with "Complete Payment"

As for Stripe, can you try testing with a stripe sandbox account? Also check if there are any errors from stripe when it tries to send the webhook. Sometimes, proxies or firewalls block incoming webhooks
