### ISSUE TITLE
Delete button doesn't work

### ISSUE THREAD

**Issue by Gh0st-cmd** [VertisanPRO/pterodactyl#186]
### Resource

WemX Pro

### Describe the issue

I found a delete button that does not work in the package edit menu --> Features when you want to delete a Features it is impossible because the href of the button is null

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.5.0

### To Reproduce

1; Go to Package Edition 2. Go to Features 3. Create Features 4. Try to Delete

### Expected Behaviour

Delete Features

### Screenshots

![Capture d'écran 2023-09-05 214742](https://github.com/VertisanPRO/pterodactyl/assets/61194866/35c83911-8265-4a6a-8867-9f6a1183a709)
![Capture d'écran 2023-09-05 214852](https://github.com/VertisanPRO/pterodactyl/assets/61194866/2256d97f-7288-4a0a-82a3-51042ade690b)

**Comment by Mubeen142** [comment]
Thanks, was fixed. If you update again, the problem is solved
