### ISSUE TITLE
WemX Pro Logo Navigation

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/pterodactyl#188]
### Resource

WemX Pro

### Describe the solution you'd like

When I click on the Logo or Brand Name in the Header, send me to the Main Page like the Logo in the Footer does, not just reload the page.

### Additional context

![https://cdn.discordapp.com/attachments/1148998321445281803/1149224713806163968/IMG_0390.png](https://cdn.discordapp.com/attachments/1148998321445281803/1149224713806163968/IMG_0390.png)

*mod edit*:
I apologize, it should've been a bug, not a suggestion

**Comment by Niclas-M2** [comment]
That's another thing, I only meant the way the Logo and Branding is just reloading the Page and not sending you to the Start Page/Portal or so

**Comment by Niclas-M2** [comment]
But ok, now we have both here 🤣

**Comment by PadowYT2** [comment]
> But ok, now we have both here 🤣

I thought it was the same issue, my bad, but I believe we can keep it

**Comment by GIGABAIT93** [comment]
I don't quite understand. Do you need to be redirected to the main page or do you need to update the page you are on?

**Comment by GIGABAIT93** [comment]
I understand the portal page?

**Comment by GIGABAIT93** [comment]
ok will be added in future versions
