### ISSUE TITLE
Right clicking in filemanager won't work

### ISSUE THREAD

**Issue by Lezarevi** [VertisanPRO/pterodactyl#19]
### Resource

Unix

### Describe the issue

Right clicking on items in filemanager places the options in a random place on the screen
![brave_Pwerd6tQgf](https://user-images.githubusercontent.com/29489719/182669763-87807ec2-258f-4d36-b00e-5b651308217c.png)

The sidebar also dissapears randomly, i've ran the theme for about 48 hours, and +-24 hours in the sidebar dissapeared again, reinstalling theme won't work to solve this.

### Pterodactyl Panel Version

1.10.1

### Resource Version

3.4.0

### To Reproduce

Go to filemanager > right click any item below the 4/5th> and look where it appears.

Sidebar disapears randomly, can't really explain.

### Expected Behaviour

When right clicking an item, it should appear below the mouse (little pointy thing?)

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/760945720470667294/850426169748488203/1067886664447447100
