### ISSUE TITLE
Server Description is displayed wrong

### ISSUE THREAD

**Issue by Niclas-M2** [VertisanPRO/pterodactyl#191]
### Resource

WemX Pro

### Describe the issue

The Server Description is displayed wrong

### Pterodactyl Panel Version

1.5.0

### Resource Version

1.5.0

### To Reproduce

tust change the Layout / Design the Text and save it, then open the Same Server/Product in the User Dashboard

### Expected Behaviour

same Layout / Design as I created in the Admin dashboard

### Screenshots

<img width="810" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/60582586/22c8625d-23f3-4d7a-a2a7-72f1b902c2b2">
<img width="232" alt="image" src="https://github.com/VertisanPRO/pterodactyl/assets/60582586/c7c711e0-7260-4969-8649-7fd9255c4fbf">

**Comment by VanillaChan6571** [comment]
Confirmed, this does happen even on the bleeding edge builds of wemx.

**Comment by VanillaChan6571** [comment]
However the [+] has been moved to the "Features" tab

**Comment by GIGABAIT93** [comment]
![зображення](https://github.com/VertisanPRO/pterodactyl/assets/59637348/e43922e5-6874-4b2a-a6b2-dd78c7653472)
this is not an error. In version 1.5.0, a separate section was added to create a description, so you need to edit the package to clear the old description and use the new feature
