### ISSUE TITLE
DONT SAVE EGG VAR

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#193]
### Product

WemX Pro

### Describe the issue

![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/88c283d3-e85f-4691-b349-533f248614b6)
when i enter my api key and and press ok its dont save this var :/

### Pterodactyl Panel Version

1.11.3

### Product Version

!:%:=

### To Reproduce

this is the curceforge egg and yes thats all i need to say

**Comment by VanillaChan6571** [comment]
api key of ptero or curseforge?

**Comment by Partymann2000** [comment]
> api key of ptero or curseforge?

the forge key dont save

**Comment by GIGABAIT93** [comment]
Will be fixed in future versions
