### ISSUE TITLE
Cannot delete package feature

### ISSUE THREAD

**Issue by uplandstatue** [VertisanPRO/pterodactyl#195]
### Product

WemX Pro

### Describe the issue

When managing packages I accidentally added a feature at 2gb of storage instead of 2gb of ram. I then went to delete the feature so I could add it correctly and once I click the red trashcan (delete) icon it simply remains highlighted and never removes the feature. I have tried to leave it for several minutes after the initial click as well as tried clicking it again with no luck. It never seems to really do anything as far as I can tell, I do not get any obvious error messages or weird actions, just nothing.

### Pterodactyl Panel Version

1.11.3

### Product Version

1.5.0

### To Reproduce

1. Log in on the admin portal
2. navigate to Products & Services > Packages
3. Edit a package
4. Navigate to features tab
5. Click the red trash icon next to an existing feature

### Expected Behaviour

I would expect it to delete the feature

### Screenshots

![bug1](https://github.com/VertisanPRO/pterodactyl/assets/51497978/3b9d7245-b45f-458b-9976-75277db3437c)

**Comment by VanillaChan6571** [comment]
This should be resolved in the next update as currently the bleeding edge dev builds don't have this issue.
