### ISSUE TITLE
Articles System

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#197]
### Product

WemX Pro

### Describe the issue

Regarding the newly added Articles system, there are a few bugs that need fixing. 1. I don't seem to be able to delete an article once its been made, it simply throws an error and does nothing (500 | Server Error). 2. The articles do not show on the News page whatsoever, which I believe is what's meant to happen? 3. There's a visual bug when editing the article on the admin panel, the link "https://example.com/pages/" where you name the page, is incorrect, as the articles get published to "https://example.com/news/examplearticle". All round great system which was needed tho, would be great if you could reply to other peoples comments.

### Pterodactyl Panel Version

1.11.3

### Product Version

1.5.0

**Comment by Mubeen142** [comment]
Hi @Shockingg 

This update has not been announced yet and is still in progress. Please reopen the issue once the update has been officially announced.

I have removed the update from the stable releases, so now if you run the docs to update you will download the previous version: 1.5.0
