### ISSUE TITLE
Ability to drag and drop the order of Categories/Packages and their display order

### ISSUE THREAD

**Issue by uplandstatue** [VertisanPRO/pterodactyl#199]
### Product

WemX Pro

### Describe the solution you'd like

In Billing V2 we were able to drag and drop the plans to create a specific order that they would display in to the customer. As far as I can tell and asking in the discord, Pro simply uses the id column in the database. While I can manually edit this in the DB it becomes a serious pain if I have any orders using a package id as I now have to move to a new table and make changes there as well.

Maybe a new column can be added to the tables for categories and packages called display_order or something that it can use to determine positioning for customer facing views and then we can manually update that through editing the category/package?

### Describe alternatives you've considered

If you aren't adding new categories often then I guess its not an issue or manual DB changes could suffice, but seems inefficient and incomplete at best.

### Additional context

A little further documentation on some features like this could be in order if this already exists?

**Comment by uplandstatue** [comment]
So, while my biggest issue was that for my use case it makes a ton of sense to be able to display those categories in a particular order, specifically to us doing so alphabetically is fine. In doing so I had a friend help me as I have no experience with php and it has been a really long time since I have done anything deeper than html/css and bash/powershell. 

We were able to come up with a solution to display the categories in alphabetical order with just two changes to the /var/www/wemx/resources/themes/client/tailwind/store/index.blade.php file. He is relatively adept with php, but not with laravel or MVC (as he said) so while we recognize this works for my current need, it is also very hacky and doesn't follow the correct architecture. Thus it is not a final solution and I am sure you will see that, but I thought I could at least share it with you in the case that it could possibly lend to better ideas or save a little footwork for a better implementation when you get there.

Though I can still where in the future being able to customize the order of them
 would be a great help and where many people may actually need that.
 
[index.blade.zip](https://github.com/VertisanPRO/pterodactyl/files/12652574/index.blade.zip)

**Comment by VanillaChan6571** [comment]
Hacky way is to change alot if "IDs" in the database itself. This could be an suggestion to add "priority view", it was tested in Features to fix the order list. So its possible to do the same with packages/categories.

**Comment by GABRIEL12e197** [comment]
..

**Comment by GIGABAIT93** [comment]
will be added in future versions
