### ISSUE TITLE
Tebex Support on billing

### ISSUE THREAD

**Issue by Davidbp99** [VertisanPRO/pterodactyl#2]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Add Tebex to the billing system https://docs.tebex.io/plugin/ so if the owner can't use paypal or stripe. Then you could use tebex that lets your clients use paypal or card without problems. Then the owner could easier transfer the money to the business bank. Could then use the ban system to ban a client off the service fully.

### Describe the solution you'd like

*read above* 

### Describe alternatives you've considered

More payments system support. Incase the owner can't use stripe or paypal.

**Comment by PadowYT2** [comment]
Just no, it is a completly different system
