### ISSUE TITLE
File manager dropdown caught off at the end

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/pterodactyl#20]
### Resource

Unix

### Describe the issue

File manager dropdown caught off at the end

### Pterodactyl Panel Version

1.10.1

### Resource Version

3.4.0

### To Reproduce

1. Go to a random server
2. Open File Manager
3. Have files there and click the 3 dots

### Expected Behaviour

It should be full size, like on Carbon

### Screenshots

![http://luigical.me/images/Screenshot_08_04_wIt2FbDd2z.png](http://luigical.me/images/Screenshot_08_04_wIt2FbDd2z.png)

**Comment by IAmTheRealLuna** [comment]
Any update on this issue as a I can reproduce it on on Pterodactyl v10.1.4 and Unix v3.5.0.1

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/760945720470667294/850426169748488203/1067886664447447100
