### ISSUE TITLE
Product extras

### ISSUE THREAD

**Issue by starrider346** [VertisanPRO/pterodactyl#200]
### Product

WemX Pro

### Describe the solution you'd like

Option to add optional extras to a plan for an increased price.

Example from OVH checkout:
![IMG_3358](https://github.com/VertisanPRO/pterodactyl/assets/58882729/5e260b64-52de-40e0-be15-cd401627e3c0)

**Comment by VanillaChan6571** [comment]
This would be great for like extra storage or ram upgrade, Im sure it can be done but **not top priority** if they saw this.

**Comment by fabsperhaps** [comment]
This fould be great. With other RAM, Stoarg, Databases, Backups etc.

**Comment by PadowYT2** [comment]
This issue has been merged into #238
