### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Shockingg** [VertisanPRO/pterodactyl#202]
### Product

WemX Pro

### Describe the issue

A weird visual bug that occurs when first generating an affiliate link, refreshing solves the issue but it shouldnt happen anyway.

![image](https://github.com/VertisanPRO/pterodactyl/assets/137300798/efc005a0-2e84-4762-9e0e-5e7486028346)

### Pterodactyl Panel Version

1.11.3

### Product Version

1.5.0

### To Reproduce

1. delete old referal links in db
2. go to affiliates page
3. see visual bug

**Comment by Mubeen142** [comment]
Thank you for your report.

The issue has been fixed
