### ISSUE TITLE
Plans are given even if payment fails.

### ISSUE THREAD

**Issue by starrider346** [VertisanPRO/pterodactyl#205]
### Product

WemX Pro

### Describe the issue

If a payment fails due to something like not enough funds for Stripe, WemxPro will still give the plan.

### Pterodactyl Panel Version

1.5.0

### Product Version

-

### To Reproduce

Begin a card payment

Have the transaction fail.

### Expected Behaviour

WemxPro doesn't give the plan.

**Comment by GIGABAIT93** [comment]
There are several Stripe gateways, can you clarify with which of them this problem occurs?

**Comment by starrider346** [comment]
Subscription 

> There are several Stripe gateways, can you clarify with which of them this problem occurs?

Subscription

**Comment by GIGABAIT93** [comment]
you can message me on Discord? I think I fixed the error, but I have no way to check it

**Comment by Mubeen142** [comment]
@GIGABAIT93 @starrider346 Was this resolved in DMS?
