### ISSUE TITLE
Language overrides 

### ISSUE THREAD

**Issue by starrider346** [VertisanPRO/pterodactyl#209]
### Product

WemX Pro

### Describe the solution you'd like

Lang file override file that is identical to how the language file works, except it starts empty. If you add a lang here, it will override whatever the main one is. 

The purpose of this file is to not get erased and replaced in an update. This would allow for people to keep their edits through updates.

**Comment by GIGABAIT93** [comment]
This feature is available from the start and is standard from laravel. You can create a file in a directory resources/lang/vendor/admin.php or module resources/lang/vendor/module_name/file_name.php
