### ISSUE TITLE
Can't get route endpoints

### ISSUE THREAD

**Issue by simonsejse** [VertisanPRO/pterodactyl#21]
### Resource

Unix

### Describe the issue

php artisan route:list
Doesn't work

### Pterodactyl Panel Version

1.10.1

### Resource Version

3.4.0 

### To Reproduce

just run php artisan route:list

### Expected Behaviour

To get a list of routes to endpoint

### Screenshots

![image](https://user-images.githubusercontent.com/20711558/183999123-115b965a-7c97-419c-afe8-0be39b8b2080.png)
![image](https://user-images.githubusercontent.com/20711558/183999026-f42becc7-7833-4e50-a991-901c21737d74.png)

### Additional Information

None

**Comment by Mubeen142** [comment]
Hi,

This issue could be caused of following reasons:
1. Server is unable to get your IP address
2. Your APP_URL in .env file is the wrong format and needs to include https://

If this didn't solve your issue, please dm me on discord and let me know you came from this github issue
