### ISSUE TITLE
API Addon System

### ISSUE THREAD

**Issue by expxx** [VertisanPRO/pterodactyl#211]
### Product

WemX Pro

### Describe the solution you'd like

Some sort of API Addon System (or an extension if it exists) to add things such as server provision modules (without you, devs of wemx, having to), or payment gateways, or just extra functionality to the panel. WHMCS is a prime example of this, just need to simplify it.

Just make the API be able to do anything to the panel. (It doesn't have to when you first release it, just progress it up to that)

### Describe alternatives you've considered

WHMCS has an amazing API, but it's implementation is garbage. It's API is not well documented at all, but it works and people have made amazing things with it.

**Comment by GIGABAIT93** [comment]
Hello, we are currently working on this, we have 1 gateway module created for demonstration, but there is no good documentation yet. https://github.com/WemXPro/gateway-example
