### ISSUE TITLE
WHMCS support

### ISSUE THREAD

**Issue by SprayerGaming** [VertisanPRO/pterodactyl#218]
### Product

WemX Pro

### Describe the solution you'd like

Add WHMCS billing module support

**Comment by expxx** [comment]
What? WHMCS Billing Module? Wemx is designed to replace WHMCS?

**Comment by SprayerGaming** [comment]
Didnt meant about that....

**Comment by expxx** [comment]
Then what did you mean?

**Comment by SprayerGaming** [comment]
Nvm,  sorry .
