### ISSUE TITLE
Checkout bug

### ISSUE THREAD

**Issue by llyrdavies** [VertisanPRO/pterodactyl#219]
### Product

WemX Pro

### Describe the issue

Ive been testing the stripe subscription gateway and it seems that on the checkout page where you're asked to enter your card information, I cannot enter my zip code as it only accepts numbers. Not sure what its like for other countries but UK zip codes at least have both numbers and letters.

### Pterodactyl Panel Version

1.11.3

### Product Version

1.6.0

**Comment by PadowYT2** [comment]
Rather a suggestion to have letters in a zip code
