### ISSUE TITLE
Coupon Bugs

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#220]
### Product

WemX Pro

### Describe the issue

If you set the voucher type to currency, the voucher amount still shows % and if you have selected currency, you cannot use commas as usual and the voucher type shows the wrong currency symbol.
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/ac1f63f7-5ac1-4db0-8ae4-61c8d144ad77)

### Pterodactyl Panel Version

1.11.3

### Product Version

1.6.0

### To Reproduce

I think I have described well

**Comment by Mubeen142** [comment]
Thanks for reporting this bug. it has been fixed for next update
