### ISSUE TITLE
Price slider

### ISSUE THREAD

**Issue by DenDanskeMine** [VertisanPRO/pterodactyl#222]
### Product

WemX Pro

## Proposal for GitHub Enhancement: Introduce a Configurable Slider for Packages

In this proposal, we recommend adding a slider feature to enhance the package configuration capabilities. This slider will allow administrators to fine-tune package settings by specifying a "name" and "value" for customers to view. For example, you could define a setting like **Player Slots**, where the value is customizable by users.

### Slider Configuration

1. **Name/Value Display:**
   - Add an option for administrators to specify a name for the slider setting, such as **Player Slots**. This name will be visible to customers during package selection.
   
2. **Price per Unit:**
   - Allow administrators to set a "price per unit" for the slider, e.g., 0.5. This will determine the cost calculation based on the user's selection.

3. **Startup Command Variable:**
   - Provide the ability to define a variable, like **{{MAX_PLAYERS}}**, which will be dynamically updated based on the user's slider selection. For example, if the user selects 10 player slots, this variable will be set to 10 in the startup command.

### Usage Scenario

Let's illustrate how this feature would work:

- If the administrator sets the price per unit to 0.5 and a user selects 10 player slots, the package price will dynamically update to $5.
- Simultaneously, the {{MAX_PLAYERS}} variable in the startup command will be set to 10.

By implementing these enhancements, package configuration becomes more flexible and user-friendly, allowing administrators to offer customizable options while simplifying the setup process for users.
### 

### Describe alternatives you've considered

none, other than making lots of packages

**Comment by VanillaChan6571** [comment]
Could be duplicated of #200 but can be added most likely.

**Comment by PadowYT2** [comment]
This issue has been merged into #238
