### ISSUE TITLE
Instead of WemX my website name should be there

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#225]
### Product

WemX Pro

### Describe the issue

There are some function e.g. at the 2fa apps and the emails there is wemx instead of my page name here are examples
1. 2FA
Unfortunately I can not make a screenshot but it says wemx

2. Emails
![image](https://github.com/VertisanPRO/pterodactyl/assets/53320411/e11d416c-f1b2-45ef-a627-185d28b0ca10)

### Pterodactyl Panel Version

1.11.3

### Product Version

1.7.1

### To Reproduce

there should be my page name instead of wemx

**Comment by VanillaChan6571** [comment]
Not a bug. You never modified the APP NAME in the .env file
