### ISSUE TITLE
Contract-Based Payments

### ISSUE THREAD

**Issue by LuluKingGithub** [VertisanPRO/pterodactyl#228]
### Product

WemX Pro

### Describe the solution you'd like

Hi,

I've recently bought WemX and as i can see, you have included the ability to apply cancellation fees. I'd love to see a module which enables the billing manager to set a subscription as a contract. This would mean depending on how many months in the user is of the duration (E.g. 12 months) if they choose to cancel - it may cost them the amount it would of costed them in that 12 month period. 

**Example**
I chose to pay for a subscription which would cost me £29.99 a month. This was set as a 24 month contract. If i had cancelled that 3 months into the contract. I'd be asked to pay £629.79 or the subscription would continue running if not able to pay.

**Comment by VanillaChan6571** [comment]
....? I will say **very VERY low priority.**

**Comment by LuluKingGithub** [comment]
But what if there is hosts that would offer dedicated servers? most of which require you to be put on a contract because of the hiked costs of even operating dedicated servers. Some hosts find contracts useful to prevent fraud. Wouldn't this be something to be put into consideration for those who use WemX? It would be a +1 optional feature to implement.

**Comment by GIGABAIT93** [comment]
the user can always unsubscribe without your consent at their bank etc so it doesn't make sense

**Comment by LuluKingGithub** [comment]
Very true, but wouldn't that lead to potential fraudalent behaviour? Like if you had someone who bought something off you and made an agreement with you to pay monthly until a certain date and then they chose to refuse paying it although it was an agreement (Like a contract). That would lead to fraud wouldn't it? You do understand my perspective? Some hosts have a big preference in keeping their customers in an contract to prevent any level of fraud. What would you suggest? For example - if my host had a dedicated server offering - we wouldn't want the user to just unsubscribe after making a 24 month agreement perhaps 3 months into it - I am aware of the cancellation fees option via the WemX panel - what would you recommend?

**Comment by GIGABAIT93** [comment]
if the user cancels the subscription, the funds are not returned, they remain with you. If I sell something for 24 months, I charge the corresponding price for that period, when the user cancels the subscription after the end of the period, he will lose access to the server/host, etc.

**Comment by LuluKingGithub** [comment]
So, your basically saying if a user cancels on a 24 month period - they'd need to pay the whole 24 months worth or a % of it?

**Comment by GIGABAIT93** [comment]
when the user buys a subscription, he immediately pays for the term you specified. That is, in the package settings, you set the price for the term you choose, and the user immediately pays for it for the term you choose

**Comment by LuluKingGithub** [comment]
I see. But what i'm referring to is, for example - if a user doesn't want to pay for a  2 years worth. And wants to pay that in a monthly fee. Which would normally be a "promise to pay for that amount bit by bit until term ends" are we still able to do that within the panel? as in are we still able to charge the user if they choose to cancel out on the agreed period early?

**Comment by GIGABAIT93** [comment]
the user can choose only the payment option that you will create in the package. He cannot purchase a package for 24 months and choose how to pay this amount himself. If you want to sell a package for 24 months, you set the appropriate price for it, if you want to sell for 1 month, then you also need to create a price for this in the package, and the user can only choose the option that you offer him

**Comment by LuluKingGithub** [comment]
Right. Not a problem. Thanks.
