### ISSUE TITLE
add subdomain manager (and custom domains if admin wants lol)

### ISSUE THREAD

**Issue by capitalized** [VertisanPRO/pterodactyl#23]
### Resource
JUST MAKE IT EASIER PLEASE!!
Plugins

### Is your feature request related to a problem? Please describe

enhance the theme/site by adding this feature to the billing module theme/site settings. this is already an existing pterodactyl plugin (subdomain manager).

for minecraft servers most likely. and or maybe all other game serverse as well

example: minecraft123.mydomain.com:PORT

csgo33.mydomain.com:PORT?

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by PadowYT2** [comment]
> ### Resource
> JUST MAKE IT EASIER PLEASE!! Plugins
Plugins are literally v1.6

And it already exists
