### ISSUE TITLE
Remove the /page prefix in the URL for custom pages

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/pterodactyl#233]
### Product

WemX Pro

### Describe the solution you'd like

Make it possible to create an Imprint, TOS, etc. in the Admin-Dashbaord which has no xzy.com/page/impring or so link, it should be directly xyzzy.com/imprint and it should be possible to have a different one for each language.

**Comment by VanillaChan6571** [comment]
/page/ will need to be required due to how nginx is setup by default etc. 

If we somehow got green light, this would most likely be an "locales modules addon" to the page system, it would use the "system/user's" default language if the language of that page does not exist then it would use the fallback of "selected default language or page". **So it most likely could work, you would need to support the translating of each "locale language/page"**. The main/first page you created, would be a "default/fallback page" if done correctly.

**Comment by PadowYT2** [comment]
> /page/ will need to be required due to how nginx is setup by default etc.
> 
> If we somehow got green light, this would most likely be an "locales modules addon" to the page system, it would use the "system/user's" default language if the language of that page does not exist then it would use the fallback of "selected default language or page". **So it most likely could work, you would need to support the translating of each "locale language/page"**. The main/first page you created, would be a "default/fallback page" if done correctly.

Didn't realy read the issue myself fully, we can remove `/page` and make a checker, but we cannot make specific language URLs

**Comment by Niclas-M1** [comment]
that would be nice, it we could create sites without the `/page`.

I meant using translations on such a page, so a User would get the Text for his language and not the one for all languages under the same link

**Comment by VanillaChan6571** [comment]
> 
> Didn't realy read the issue myself fully, we can remove `/page` and make a checker, but we cannot make specific language URLs

Why not? Its not "impossible" might need a slight modification. example you could have "nekohosting.gg/page/tos=?en" but if the user default language is Spanish, it could try "nekohosting.gg/page/tos=?es" if else/invalid default back to the normal page?

**Comment by Niclas-M1** [comment]
that would be a great way, maybe we could create the different versions for the different languages directly on the sites page.

Maybe we could use this system with a checker on all pages, so we could also use this system for info-pages, etc.
(maybe it would be extended to the news system as well?)

**Comment by PadowYT2** [comment]
> > Didn't realy read the issue myself fully, we can remove `/page` and make a checker, but we cannot make specific language URLs
> 
> Why not? Its not "impossible" might need a slight modification. example you could have "nekohosting.gg/page/tos=?en" but if the user default language is Spanish, it could try "nekohosting.gg/page/tos=?es" if else/invalid default back to the normal page?

True, but would be hard and really unnecessary

**Comment by VanillaChan6571** [comment]
> > > Didn't realy read the issue myself fully, we can remove `/page` and make a checker, but we cannot make specific language URLs
> > 
> > 
> > Why not? Its not "impossible" might need a slight modification. example you could have "nekohosting.gg/page/tos=?en" but if the user default language is Spanish, it could try "nekohosting.gg/page/tos=?es" if else/invalid default back to the normal page?
> 
> True, but would be hard and really unnecessary

@Mubeen142 or @GIGABAIT93 might have a better solution since he knows the code better. 

As I said before this would have to be a green lit idea/project. Other than that, it mostly a suggestion that I could see being useful in some cases.

**Comment by GIGABAIT93** [comment]
we can add it for /page but you have to manually create the translation for each language. And I think the url will not have to be changed to get the desired language, we can immediately return the desired language if the translation exists. I will try to implement it

**Comment by Niclas-M1** [comment]
that sounds great

**Comment by GIGABAIT93** [comment]
that you can also add a translation to the page titles as shown here https://github.com/WemXPro/languages/blob/main/en.json
![зображення](https://github.com/VertisanPRO/pterodactyl/assets/59637348/f31b419d-a450-4be5-acfa-e130ba57cac5)
![зображення](https://github.com/VertisanPRO/pterodactyl/assets/59637348/3edc039a-d471-49d6-b109-3a7c93fd40ad)

**Comment by GIGABAIT93** [comment]
as for the /page prefix, we cannot remove it because it will disrupt the operation of all routes and the site will not work because it expects a dynamic argument immediately after the domain. We can change it but not delete it

**Comment by GIGABAIT93** [comment]
Added page translation will be available in future updates
