### ISSUE TITLE
add czech currency (CZK)

### ISSUE THREAD

**Issue by Gresakm** [VertisanPRO/pterodactyl#234]
### Product

WemX Pro

### Describe the solution you'd like

Adding support for Czech currency (czk) for wemx. The currency for the whole wemx site could be set to Czech currency (czk).

**Comment by PadowYT2** [comment]
You can add the currency in `config/utils.php` (or something similar)

**Comment by Gresakm** [comment]
Then we'll have to look for another solution because of your reluctance...

**Comment by PadowYT2** [comment]
> Then we'll have to look for another solution because of your reluctance...

Sorry, what do you mean? We have added small amount of currencies, it is really easy to add currencies in the config file, just 3 lines of naming and that's it
