### ISSUE TITLE
add fastdownload to the script:)

### ISSUE THREAD

**Issue by capitalized** [VertisanPRO/pterodactyl#24]
### Resource

Plugins

### Is your feature request related to a problem? Please describe

add fastdownload to billing module theme/settings

### Describe the solution you'd like

add fastdownload to billing module theme/settings

**Comment by PadowYT2** [comment]
> ### Resource
> JUST MAKE IT EASIER PLEASE!! Plugins

Plugins are literally v1.6

### It is a different addon, so no
