### ISSUE TITLE
Revenue Graph should not add up if the gateway of "balance credit" was used.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#241]
### Product

WemX Pro

### Describe the issue

The Graph will count both Bought Service and Balance Top Up, basically "doubling" the "Revenue" which is false since the "service" was bought via "Top Up" meaning its free.

### Pterodactyl Panel Version

N/A

### Product Version

WEMX 1.7.2

### To Reproduce

1. Buy a service via Top Up
2. The Graph indicates that you made X amount when in reality they already paid for the X amount with Balance Top Up.

### Expected Behaviour

It would not add up since the gateway is "Credit Balance" and not Manual/Renew Types.

**Comment by GIGABAIT93** [comment]
will be fixed in future versions
