### ISSUE TITLE
Missing Buttons for servers in dashboard when theme is installed

### ISSUE THREAD

**Issue by Crimson7806** [VertisanPRO/pterodactyl#242]
### Product

WemX Pro

### Describe the issue

When I use an unaltered theme, (copy pasting the default theme) The buttons to manage a server do not appear to work, not sure if this is user error on my part when it comes to setting up a theme or a bug 

### Pterodactyl Panel Version

1.11.5

### Product Version

1.7.2

### To Reproduce

1. Copy Tailwind theme file and rename it to something random, same with the theme.php
2. Head to domain.com/dashboard and select a server.
3. Observe.

### Screenshots

![With Default Theme](https://github.com/VertisanPRO/pterodactyl/assets/52816073/76697cc5-61ac-4aba-b778-2ceae44af59e)
![Without Default Theme](https://github.com/VertisanPRO/pterodactyl/assets/52816073/fa1c5a12-1475-4a5e-ba15-351ea81d3b95)

**Comment by Mubeen142** [comment]
Hi @Crimson7806 

This issue is caused since you are using a custom theme.

In file /app/Services/Pterodactyl/Resources/views/ duplicate the "tailwind" folder to the new theme folder
