### ISSUE TITLE
Button sends to /notifications

### ISSUE THREAD

**Issue by DAMO11-coder** [VertisanPRO/pterodactyl#248]
### Product

WemX Pro

### Describe the issue

In the Admin Panel, when you click on the bell icon, notifications appear. However, at the bottom, there's a 'View All' button. Clicking this button redirects the user to /notifications, but unfortunately, they are met with a 404 Error.

### Pterodactyl Panel Version

latest

### Product Version

latest

### Screenshots

![image](https://github.com/VertisanPRO/pterodactyl/assets/77869423/c06a7f86-bf3d-4191-a3e6-e4dbc8a71734)

![image](https://github.com/VertisanPRO/pterodactyl/assets/77869423/d6fcc3b5-b957-4518-8ee4-31e697c44736)

### Additional Information

Mod edit: button must be removed

**Comment by Mubeen142** [comment]
Thanks for the report, the button has been removed
