### ISSUE TITLE
revenue its at 0 now

### ISSUE THREAD

**Issue by rickoffthewall1** [VertisanPRO/pterodactyl#249]
### Product

WemX Pro

### Describe the issue

 just did the update i think there is an issue its not picking up the revenue its at 0 now

### Pterodactyl Panel Version

1.11.4

### Product Version

v1.8.0

**Comment by VanillaChan6571** [comment]
Just tested. Working as intended.

**Comment by rickoffthewall1** [comment]
its not working for me how can i fix it its saying my revenue is 0 after the new update i restarted a few times as well

**Comment by Mubeen142** [comment]
Hi @rickoffthewall1 

Thanks for your report.

The bug has been fixed and will be available in the next update
