### ISSUE TITLE
Cancel on due date (end of term)

### ISSUE THREAD

**Issue by smcfreak** [VertisanPRO/pterodactyl#25]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Currently if you cancel a plan, it will delete it immediately, no matter how many pre-payments one has made.
There is also **no refund**! If someone cancels by mistake, their data is gone and their money as well. This will cause only issues and more issues.
And before some of you complain about these mistakes, if a client has 20 plans, mistakes like these can easily happen and the data is gone. (the warning is not enough)

In my case, the cancellation of a plan even caused a DB error that I will try to fix now.

### Describe the solution you'd like

Simply add an option to cancel at the end of term in addition to immediately. 
Cancellation handling would be best if similar setup to WHMCS, where you as an admin have to check the cancellation request and confirm it.

**Comment by Mubeen142** [comment]
Hi @smcfreak 

Just implemented a new cancellation system. The server will now be cancelled but not deleted until the server is paid for. After that the server will be suspended. During the grace period the user will have the option to continue their subscription at any time.

https://cdn.discordapp.com/attachments/899358123565908009/1028595277080318052/unknown.png
