### ISSUE TITLE
New tax rates UK

### ISSUE THREAD

**Issue by sambrown03** [VertisanPRO/pterodactyl#250]
### Product

WemX Pro

### Describe the solution you'd like

UK, 20% and United Kingdom

I have added these to the config/tax.php but seems like the tax is still not adding onto the orders.

**Comment by Mubeen142** [comment]
Hi @sambrown03 

Thank you for your suggestion.

I have added the following tax settings for UK

```php
        "GB" => [
            "country" => "Great Britain",
            "vat_name" => "VAT and duties",
            "vat_abbr" => "VAT",
            "standard_rate" => 20,
            "reduced_rate" => 5,
            "reduced_rate_alt" => false,
            "super_reduced_rate" => false,
            "parking_rate" => false,
        ],
```
