### ISSUE TITLE
Incorrect payout text

### ISSUE THREAD

**Issue by llyrdavies** [VertisanPRO/pterodactyl#253]
### Product

WemX Pro

### Describe the issue

Minor bug but it seems that some html that has appeared where affiliates cashout their money to balance:

![image](https://github.com/VertisanPRO/pterodactyl/assets/146123002/10e7228f-c5b3-488d-a9c5-94eabf3e3910)

### Pterodactyl Panel Version

1.11.5

### Product Version

1.8.1

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
