### ISSUE TITLE
Nulled button

### ISSUE THREAD

**Issue by llyrdavies** [VertisanPRO/pterodactyl#254]
### Product

WemX Pro

### Describe the issue

Minor bug but the button displayed in the screenshot below seems to be nulled out, it still copies to clipboard but it doesnt say so like it should.

![image](https://github.com/VertisanPRO/pterodactyl/assets/146123002/be83a026-ee4c-4a95-ac28-cfb0a5a0d56e)

### Pterodactyl Panel Version

1.11.5

### Product Version

1.8.1

**Comment by GIGABAIT93** [comment]
did not understand what exactly is wrong? can you explain in more detail

**Comment by llyrdavies** [comment]
Pretty much when you click the button it redirects to /# instead of saying "Copied" like it used to.

**Comment by GIGABAIT93** [comment]
буде виправлено у наступні версії
