### ISSUE TITLE
Wrong amount

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#255]
### Product

WemX Pro

### Describe the issue

If you set it so that you get the plan cheaper the first time you buy, you always get the server for the first price and not for the second price

https://github.com/VertisanPRO/pterodactyl/assets/53320411/7cb6f8ab-e64f-42d6-b9c1-36de636a615a

### Pterodactyl Panel Version

1.11.3

### Product Version

1.8.1

**Comment by Partymann2000** [comment]
> That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8

Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8

**Comment by PadowYT2** [comment]
> > That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8
> 
> Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8

So, what's the problem?

**Comment by Partymann2000** [comment]
> > > That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8
> > 
> > 
> > Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8
> 
> So, what's the problem?

The problem is that you only pay 7.50 and not the 8

**Comment by PadowYT2** [comment]
> > > > That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8
> > > 
> > > 
> > > Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8
> > 
> > 
> > So, what's the problem?
> 
> The problem is that you only pay 7.50 and not the 8

Because the first month is 7.5

**Comment by Partymann2000** [comment]
> > > > > That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8
> > > > 
> > > > 
> > > > Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8
> > > 
> > > 
> > > So, what's the problem?
> > 
> > 
> > The problem is that you only pay 7.50 and not the 8
> 
> Because the first month is 7.5

Yes, exactly, but after the first purchase you would actually have to pay 8, but you can always and always buy again for 7.50

**Comment by VanillaChan6571** [comment]
> 
> Yes, exactly, but after the first purchase you would actually have to pay 8, but you can always and always buy again for 7.50

What the f- are you on about? Then swap the first month to $8 then $7.50 for repeat.

This is the dumbest issue Ive seen this year. Please lock this thread/post. they have no idea what they are doing.

**Comment by PadowYT2** [comment]
> > > > > > That's how you made it, you have set the first month price to 7.5$ and then after the month, the customer is going to pay $8
> > > > > 
> > > > > 
> > > > > Yes exactly, I have set it so that when you buy the plan for the first time that you add 7.50 and after that you have to pay 8
> > > > 
> > > > 
> > > > So, what's the problem?
> > > 
> > > 
> > > The problem is that you only pay 7.50 and not the 8
> > 
> > 
> > Because the first month is 7.5
> 
> Yes, exactly, but after the first purchase you would actually have to pay 8, but you can always and always buy again for 7.50

I understood you, unfortunately it is pratically impossible to defeat this kind of abuse. This is up to the hosting to see this kind of activity and prevent it
