### ISSUE TITLE
employee account or role

### ISSUE THREAD

**Issue by rickoffthewall1** [VertisanPRO/pterodactyl#257]
### Product

WemX Pro

### Describe the solution you'd like

I think having an employee account or role could be useful. I'm not sure about others, but if employees are helping out, we want them to access plans and create voucher codes. However, we don't want them to access things like payment gateways it would be helpful if we can get a menu like the one in pterodactyl were you make a sub user and can select which permission you want to give them.

**Comment by PadowYT2** [comment]
You can already make a new group with the permissions you want
