### ISSUE TITLE
Edit plans all in one page instead of two seperate pages

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#26]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Often times we have problems sorting out a large list of games when going page to page just tring to add plans to a game added onto the list. I wanted to introduce a suggestion where we can edit our plans all on one page and make life a whole lot easier and the website alot more flexible to work with.

### Describe the solution you'd like

i have a feature request to make life alot easier for us to edit our plans.

Instead of seperating games with plans, why dont we have them in a categorized in one tab

For example
```
Minecraft [/ (Edit Section)] [bin] [^]
\ Plan 1 [/ (Edit Plan)] [bin]
\ Plan 2 [/ (Edit Plan)] [bin]
\ Plan 3 [/ (Edit Plan)] [bin]
```

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
