### ISSUE TITLE
Text outside button, new service

### ISSUE THREAD

**Issue by Gresakm** [VertisanPRO/pterodactyl#260]
### Product

WemX Pro

### Describe the issue

Before the update to 1.8.1, the button was enlarged and the text was on 2 lines. Now the second line is not created, so the text does not fit in the button.

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.5

### To Reproduce

1. Log into the site on mobile https://example.web
2. Go on mobile to https://example.web/dashboard

### Expected Behaviour

All visible text "Order new service" and "Add balance" on the button.

### Screenshots

![Screenshot_2023-11-09-15-37-28-605_com brave browser](https://github.com/VertisanPRO/pterodactyl/assets/137584356/a681734d-6667-45be-8d6e-e322fcb1db17)

### Additional Information

The text "Add balance" is visible in the button but when the text is extended it also does not fit into the button.

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
