### ISSUE TITLE
Add Readmore buttons

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#276]
### Product

WemX

### Describe the issue

If you go to /store, or in the portal by the selectet categories for example, and have made the category descriptions different lengths, the fields are also different sizes - perhaps you could shorten the text from 3 lines or perhaps even from 2 and then add read more so that the design is uniform.

### Product Version

1.8.1

### Pterodactyl Panel Version

1.11.3

**Comment by nabeelimrani** [comment]
its added for the next update.
