### ISSUE TITLE
Chargeback Issue

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#28]
### Resource

Billing

### Describe the issue

Members were able to buy and charge back on there services, allowing them to continue using the servers freely. we removed there server but the plan still exsist on the billing panel.

### Pterodactyl Panel Version

1.11.2

### Resource Version

2.5.5

### To Reproduce

Costomer creates an account
Costomer Adds creditd using paypal
Costomer buys a server
Costomer charges back

Admin Removes server

### Expected Behaviour

Plan should shoe that the costomer charged back
Costomer should have a negative in there balance 

Plan Expires after admin deletes server

**Comment by Mubeen142** [comment]
Hi,

This is not a bug rather a feature request. Currently it's not possible to implement this for PayPal payments as it requires a PayPal business account and our api is made for personal PayPal accounts as most users dont have a PayPal business account

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
