### ISSUE TITLE
per plan allocations

### ISSUE THREAD

**Issue by epictroller629** [VertisanPRO/pterodactyl#3]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Yes.

### Describe the solution you'd like

per plan allocations

### Describe alternatives you've considered

per plan allocations

### Additional context

per plan allocations

**Comment by xDeathWizard** [comment]
should be added for next update, very useful + kind of annoying when every server has the main mc ports

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
