### ISSUE TITLE
Register Now (Very Minor, Not Major)

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#32]
### Resource

Billing

### Describe the issue

Users still see Register Now when they are logged onto the panel.

### Pterodactyl Panel Version

1.10.1

### Resource Version

2.5.5

### To Reproduce

Login to the panel, go to portal, and Register now still exists.

### Expected Behaviour

Replaced the Register now with Manage Servers

### Screenshots

![image](https://cdn.discordapp.com/attachments/761812399262662661/1015477992148971520/unknown.png)

**Comment by AuroraRpg** [comment]
I would say that something like this might work
![image](https://user-images.githubusercontent.com/23438816/188256619-2c4afba7-022c-4b7a-a44a-39d80f99b178.png)

**Comment by Mubeen142** [comment]
Thanks for the report, will be looked at next update :)

**Comment by Mubeen142** [comment]
Hi Zeropoint,

Thanks for your bug report. I've just fixed the issue and will be available next update :)
