### ISSUE TITLE
Generate Sitemap, and Allow Robots.txt

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#33]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Ok so, I've noticed two things the billing node is lacking.
1 : Robots.txt is set to disallow everyone from seeing the website from the search engine
2 : There is no Sitemap Generated by the billing node, Its essential when you want to add it onto search engines like Google Webmaster, Bing SearchMaster, and Yandex Search Master.

### Describe the solution you'd like

I Would like the following to change

1: robots.txt in /var/www/pterodactyl/public/
```
User-agent: *
Allow: /
```
Kinda like the one I have currently on my website https://banabyte.com/robots.txt

2: Generate Sitemap.xml in /var/www/pterodactyl/public/
Kinda like the one I have here on my website https://banabyte.com/sitemap.xml

### Describe alternatives you've considered

I've Changed robots.txt manually and used a Sitemap Generator.

**Comment by MyShoesHaveSplinters** [comment]
This would be a great feature to add, so customers can find the website on google.

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
