### ISSUE TITLE
Editing Games will show up blank when the Game on billing tab already exsists.

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#34]
### Resource

Billing

### Describe the issue

Sorry, I feel like I'm slamming you guys but This has been a bug ever since the 2.3.0 Update for the billing node where you add a game to the billing service, then later try to edit it later on, and the tabs will show up blank. Right? Even if I added the same name, the error I would get is Sorry but this game already exists.

Yet when I goto the MySQL table, i can change it from there and everything is fine

### Pterodactyl Panel Version

1.10.1

### Resource Version

2.5.5

### To Reproduce

1: Create a Game on the billing module under the administration tab
2: Edit the game
Like so ![Image1](https://i.imgur.com/gBgQwNk.png)
3: ![Problem](https://i.imgur.com/bDAmPgs.png)
4: ![Error](https://i.imgur.com/xia5tf7.png)
5: ![MySQL Table](https://i.imgur.com/M6TzHmG.png)

### Expected Behaviour

To edit the Game on the list

### Screenshots

![Image1](https://i.imgur.com/gBgQwNk.png)
![Problem](https://i.imgur.com/bDAmPgs.png)
![Error](https://i.imgur.com/xia5tf7.png)
![MySQL Table](https://i.imgur.com/M6TzHmG.png)

**Comment by WarToWin** [comment]
Yea it weirdly happened to me as well sometimes when i try to edit it.

**Comment by Mubeen142** [comment]
Hey @ZEROPOINTBRUH 

Thank you for the elaborate report. I've tried to look into this but I'm not sure if I exactly understand the problem.

I just made some changes to the code that will give the user an error without reloading when users creates a new game with missing fields. Is this what you meant? Please let me know.

![image](https://user-images.githubusercontent.com/58806240/194764739-2830b615-c9cf-42a2-8514-5afd1919a540.png)
