### ISSUE TITLE
Automatic Server Renewal [!!NOT RELATED TO AUTOMATIC PAYMENTS!!]

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#35]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Some members with credit in there account with to use there servers without manually renewing the plan. I had a client complain that they lose members on a game server because of the manual renewal.

### Describe the solution you'd like

Automatic renewal of plans
If the person has credits in their account, they can use that to renew their server plan automatically until they're out of credits.
When they are out of credits and their server about to hit automatic renewal, an email should be sent out that they're low on credits.

### Describe alternatives you've considered

There is no alternative

**Comment by BethDevJS** [comment]
Definately thing this is something that should be added, my users are having their servers suspended even if they have enough money in their balance

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
