### ISSUE TITLE
Suspend user accounts and login to a user account with a single button.

### ISSUE THREAD

**Issue by Huguitis** [VertisanPRO/pterodactyl#37]
### Resource

Billing

### Is your feature request related to a problem? Please describe

In part, yes, when I want to suspend a server, for example, it does not work since the user can delete it even if it is suspended and can create another one that is not (if the plan is free)

And about logging into a user's account with a single button, I think it would be very useful to delete a user's plan (without deleting the server from the admin tab because then there is an error if then the user enters the "My plans" tab) for example.

### Describe the solution you'd like

Suspend user accounts feature. (Doing this will also suspend the servers automatically.)
Login to a user account with a single button feature.

**Comment by Mubeen142** [comment]
Hi,

We've added your request of allowing admins to impersonate clients in the next update :)
