### ISSUE TITLE
A Overhaul for the clients panel

### ISSUE THREAD

**Issue by Repoman603** [VertisanPRO/pterodactyl#39]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Personal

### Describe the solution you'd like

Listen up, I like what you guys have implemented, but the problem is the theme that it came with.

Keep in mind, that I am not a customer of the billing node, I am a consumer who invested in another server's network. I just made a GitHub account to state my problems with the panel because the people who own the billing node said it's out of their reach to edit any of the code as it's mostly proprietary code.

So let's begin with the opening statement.

Out of the box, the portal, and login screen, looks beautiful. But the issues don't pertain to the portal page. When you signup to the website, the client panel is a huge mess.

Here's what I'm saying
It's hard to navigate around the client panel
Ordering and Payments are two of the most difficult systems to go through because you have to add credit to your account just to order the server
one you add credit you your account
The next step is ordering the items you have. except you have to fill your cart again with the items you just tried to order.
once you complete the order, you are greeted with this page where the buttons take up most of the screen, it's atrocious.
The server buttons are way too large on the side, which makes it hard to navigate around. 
Some boxes like the Minecraft EULA take up almost 40 percent of the dead center of my screen just to make me agree to the tos.
The 2step authentication requires you to scroll down just to notice you have to enter a password into the box.
And the way you do payments makes you feel like you're signing up to one of those sketchy gambling websites from 2014.

The whole theme just needs an overhaul.

Here are some suggestions i can think off of at the top of my head. please keep in mind, i'm not a genius coder, i'm just a consumer so if it sounds crazy what i say i apologize but i want to finish up what i have.

First, Reduce rhe massive button sizes, its crazy how enlarged they are to my screen. I have to zoom out 50% just to atleast make it look half decent.

Second, The shopping cart should be the area to purchase your servers, credits is just a ridiculous system in my opinion.

Third, A proper terms of service area. These guys have no terms of service on there website, anyone can easily abuse the website and noones left liable.

Fourth, Reduce the ui sizes of boxes. They litterally eat up space on my monitor. are you guys insane.

Fifth, if your going to keep the credit system, atleast tey to make it not look like i'm signing myself up on a forgien casino from 2014 and give it a more professional look.

and sixth, get rid of alert boxes, they are atrocious.

Thats all i have, i never use github or plan on doing so anyway. but thank you for your time.

### Describe alternatives you've considered

There are no alternatives 

### Additional context

There are no alternatives

**Comment by Mubeen142** [comment]
Hey @Repoman603 

Thanks for your report. I agree with you on some points, I myself would rather have direct payments instead of going through multiple pages to add credit then buy server etc...

It's some of the things we are working on in the future for the Billing system. We want to make it separate from Pterodactyl which will allow a lot more possibilities. For now, we are continuing with current system but I will definitely keep your suggestions in mind. Thank you
