### ISSUE TITLE
IP Check for new registers / Required to link external accounts to buy plans

### ISSUE THREAD

**Issue by Huguitis** [VertisanPRO/pterodactyl#4]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Yes, there are users who create more than one account and abuses it to create more free servers

### Describe the solution you'd like

That the program saves the ips of the registered users and makes possible to only create an account with the same ip. They will be able to create more with vpn but it would be another security barrier.
Also the users can link their panel accounts with other accounts from other services, such as google or discord and that it can be configured so that if they want to create a server they need to link them.
These options could be optional and configurable from the admin section.
Thanks.

**Comment by Davidbp99** [comment]
Something better then this would be where admins needs to approve an account before they can buy something (should be toggle due). As some hosting company do. Run ID checks and cross reference public data or what you would like to check on.

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
