### ISSUE TITLE
Servers deleted by 10 days

### ISSUE THREAD

**Issue by PadowYT2** [VertisanPRO/pterodactyl#40]
### Resource

Billing

### Describe the issue

Servers are deleted by the end of 10 days even when it is turned off

### Pterodactyl Panel Version

1.10.1

### Resource Version

2.5.5

### To Reproduce

1. Disable server deletion
2. Wait 10 days

### Expected Behaviour

It should not be deleted

**Comment by Mubeen142** [comment]
Hi Padow,

Thanks for your bug report! I've checked the code and you're right. I've just fixed the issue and will be available next update :)
