### ISSUE TITLE
Billing Node Breaks Schedules 

### ISSUE THREAD

**Issue by MyShoesHaveSplinters** [VertisanPRO/pterodactyl#41]
### Resource

Billing

### Describe the issue

Schedules on normal pterodactyl works, but when i install billing node over it. The Feature breaks.

### Pterodactyl Panel Version

latest

### Resource Version

2.5.5

### To Reproduce

1 Create Server
2 Add Schedule
3 Schedule will not run automaticly

### Expected Behaviour

Scheduled Task

**Comment by PadowYT2** [comment]
#13
