### ISSUE TITLE
Billing node Emails cant be sent out

### ISSUE THREAD

**Issue by MyShoesHaveSplinters** [VertisanPRO/pterodactyl#42]
### Resource

Billing

### Describe the issue

Emails can't be sent out for new users signing up

### Pterodactyl Panel Version

latest

### Resource Version

2.6.0

### To Reproduce

1 Enter the website
2 Enter The Registration Page
3 Register
4 Account was created, Email failed to send

### Expected Behaviour

Email has been sent

**Comment by MyShoesHaveSplinters** [comment]
and no, i made sure my smtp server is connected

**Comment by PadowYT2** [comment]
1. Please use discord to get support
2. Latest is not a version
