### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#424]
### Describe the issue

If you have the admin panel in dark mode you can't see the control box but in whitemode it works
![image](https://github.com/WemXPro/tracker/assets/53320411/a3eabf47-a93e-4f86-b16f-4823764418b5)

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

-

**Comment by Mubeen142** [comment]
thanks for reporting this, it will be fixed next update
