### ISSUE TITLE
a bug (no definition)

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#425]
### Describe the issue

If you edit a user and then click on Orders --> Create, the user who is currently editing the user is always selected as the user but not the user
here this is my user
![image](https://github.com/WemXPro/tracker/assets/53320411/a1e0ece3-f7f3-4c60-a412-5e11bd4b5dd2)
when i press on create in orders
![image](https://github.com/WemXPro/tracker/assets/53320411/a4feaa2d-60fd-487b-ae25-c2634953829e)
he does not use the edited user

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

-

**Comment by Mubeen142** [comment]
thank you for reporting this, it was fixed
