### ISSUE TITLE
Reward System for Billing

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#43]
### Resource

Billing

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Adding a possible reward system so that you can, for example, get some credit every day and maybe also that you can have a strike so that you get more money on the 2nd day.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
