### ISSUE TITLE
oAuth login/register Bug

### ISSUE THREAD

**Issue by Niclas-M1** [VertisanPRO/pterodactyl#434]
### Describe the issue

The registering is disabled, a user can still create an account, by using the login using the oAuth Methods, then an Account will be created - please fix

### Product Version

2.1.0

### To Reproduce

1. disable registration in Admin-Dashboard
2. login using oAuth into a non existing User -> User get's created

### Expected Behaviour

Registration should not be possible

**Comment by GIGABAIT93** [comment]
Will be fixed in the next update
