### ISSUE TITLE
Categories Logo

### ISSUE THREAD

**Issue by TheUndeadRedneck** [VertisanPRO/pterodactyl#439]
### Describe the issue

When you set the categories logo during the initial creation of the category everything works fine, however when you go to change the logo to something different or an updated resolution the logo does not change. I have tried this on 2 different browsers as well as cleared the cache on both.

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

N/A

### To Reproduce

1. Click Categories
2. Create a category and upload an image
3. Edit the Category 
4. Attempt to replace the logo

### Expected Behaviour

The logo to update with the new image and or resolution

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
