### ISSUE TITLE
Default Images not loading due to Cloudflare

### ISSUE THREAD

**Issue by KoDevV2** [VertisanPRO/pterodactyl#441]
### Describe the issue

Default images that are hosted on the wemx cdn are being blocked by Cloudflare, which prevents the images from being loaded

### Product Version

2.1.0

### To Reproduce

1. Go to any self hosted wemx site with the default portal theme
2. ctrl + shift + i 
3. go to networks
4. all 3 images will be blocked with 403 response code, and additional information by Cloudflare in the response headers

### Expected Behaviour

Images should show properly instead of being blocked by Cloudflare

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/134250441/0aa8e708-e6b3-435f-97fe-da3b02346959)
![image](https://github.com/WemXPro/tracker/assets/134250441/c6da5707-b668-4fcc-88a1-328ebbfff314)

**Comment by XceptDev** [comment]
Yes, this is right, same with minecraft image.
![image](https://github.com/WemXPro/tracker/assets/77639981/1e62d3bc-71ac-4ebf-8d02-4299eee08c33)
