### ISSUE TITLE
OAuth User Creation

### ISSUE THREAD

**Issue by joti-prime** [VertisanPRO/pterodactyl#444]
### Describe the issue

When a user is created through oAuth, the email says WemX instead of the company name. 

### Product Version

2.1.0

**Comment by GIGABAIT93** [comment]
it's strange because the code doesn't say that, make sure you change the name in the settings because the code uses it
![зображення](https://github.com/WemXPro/tracker/assets/59637348/05a4e49c-7232-4b00-9ea9-a97a473fd5b3)

**Comment by joti-prime** [comment]
Hello is a code problem, I don’t know if Mubeen already fix it, but he told me this and it works:

edit file app/Http/Controllers/Auth/OauthController.php

replace 

```
config('app.name')
```

with

```
settings('app_name')
```

**Comment by GIGABAIT93** [comment]
so it's already fixed
