### ISSUE TITLE
Cyryllic symbols doesn't print in the invoice

### ISSUE THREAD

**Issue by lofihip** [VertisanPRO/pterodactyl#445]
### Describe the issue

When i try to generate an invoice on RUS or UA languages i get question mark symbol instead of the cyryllic symbols.
 

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

1.11.5

### To Reproduce

1. Set the RU or UA language. 
2. Top up the balance 
3. Print the invoice 

### Expected Behaviour

Instead of ???????????? i should get the normal cyryllic symbols.

### Screenshots

![Screenshot_1](https://github.com/WemXPro/tracker/assets/45395799/80e7f9ff-2bee-47dd-a5e3-509277d04f45)

**Comment by GIGABAIT93** [comment]
will be fixed in the next update
