### ISSUE TITLE
Database Setup does not distribute proper permissions

### ISSUE THREAD

**Issue by MyShoesHaveSplinters** [VertisanPRO/pterodactyl#45]
### Resource

Billing

### Describe the issue

Billing node breaks database permission base

### Pterodactyl Panel Version

latest

### Resource Version

2.6.0

### To Reproduce

1: Create Database on gameserver
2: Database is created but with no permissions

### Expected Behaviour

Database is created with read and write permissions

### Additional Information

Billing node causes the issue
Standard Pterodactyl dosn't

**Comment by PadowYT2** [comment]
This doesn't make sense, elaborate

**Comment by MyShoesHaveSplinters** [comment]
when a costomer recives a server and creates a database, the database will be created but with no permissions to read any data or write. i have tested this on a stable build of pterodactyl and never had an issue with it, when i've installed the billing node and have created the server, then add a database to it, the database will create on the server but the database was not given permissions by pterodactyl

**Comment by PadowYT2** [comment]
Makes absolutelly no sense, even if it is not given perms, does it really matter?

**Comment by ZEROPOINTBRUH** [comment]
Its either an issue with your mariadb setup or pterodactyl has no permissions given by the client who created the user in mariadb
