### ISSUE TITLE
IP Ban bans (suspends) everyones account

### ISSUE THREAD

**Issue by joti-prime** [VertisanPRO/pterodactyl#451]
### Describe the issue

I banned one person with ip ban and everyone (including me) was ban (suspended)

### Product Version

 2.1.0

**Comment by PadowYT2** [comment]
You probably had Cloudflare Proxy enabled without [Cloudflare Proxy Filter](https://docs.wemx.net/en/setup/cloudflare-proxy-filter)

**Comment by joti-prime** [comment]
I have the CloudFlare filter enabled, I see different IPs in each user so is working fine. Another thing? Is working in yours?

**Comment by PadowYT2** [comment]
> I have the CloudFlare filter enabled, I see different IPs in each user so is working fine. Another thing? Is working in yours?

I haven't tested myself, but if your Cloudflare Proxy Filter enabled, then I'll reopen

**Comment by Mubeen142** [comment]
@PadowYT2 

So if WemX already kept track of cloudflare ips and you enable the cloudflare filter afterwards those ips are still stored in the database. did you purge them before you tested this?

**Comment by PadowYT2** [comment]
> @PadowYT2
> 
> So if WemX already kept track of cloudflare ips and you enable the cloudflare filter afterwards those ips are still stored in the database. did you purge them before you tested this?

I have not tested this

**Comment by joti-prime** [comment]
@PadowYT2 Will be solved in the new version? Have you tested if it works?

**Comment by PadowYT2** [comment]
> @PadowYT2 Will be solved in the new version? Have you tested if it works?

I will write an explanation in Discord later today

**Comment by EWANZO101** [comment]
@joti-prime  its been tested by myself and works  along with padow s help so it should be easy for anyone to follow once ** padow explanation in Discord later today **

**Comment by joti-prime** [comment]
Excellent, will wait the explanation.

**Comment by Mubeen142** [comment]
Hello @joti-prime 

I did just test this again and you are right it did ban me too. I am not sure why it works on some systems and it doesnt work on others.

I have made some changes to the model file, try to replace this model on your server and check if that solves it.

Replace file `app/Models/Punishment.php` with

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Model;

class Punishment extends Model
{
    use HasFactory;
    protected $table = 'punishments';

    protected $casts = [
        'expires_at' => 'datetime',
    ];

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function staff(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function unban()
    {
        $this->type = 'unbanned';
        $this->expires_at = now();
        $this->save();
    }

    public static function hasActiveBans()
    {
        $ban = Punishment::where('type', 'ipban')->where('ip_address', request()->getClientIp())->first();
        if ($ban) {
            if (isset($ban->expires_at) and $ban->expires_at->isPast()) {
                return false;
            }

            return true;
        }

        $user = auth()->user();
        if ($user) {
            $ban = Punishment::where('type', 'ban')->orWhere('type', 'ipban')->where('user_id', $user->id)->first();
            if ($ban) {
                if (isset($ban->expires_at) and $ban->expires_at->isPast()) {
                    return false;
                }

                return true;
            }
        }

        return false;
    }

    public static function getActiveBan()
    {
        $ban = self::where('type', 'ipban')->where('ip_address', request()->getClientIp())->first();
        if ($ban) {
            if (isset($ban->expires_at) and $ban->expires_at->isPast()) {
                return false;
            }

            return $ban;
        }

        $user = auth()->user();
        if ($user) {
            $ban = Punishment::where('type', 'ban')->orWhere('type', 'ipban')->where('user_id', $user->id)->first();
            if ($ban) {
                if (isset($ban->expires_at) and $ban->expires_at->isPast()) {
                    return false;
                }

                return $ban;
            }
        }

        return false;
    }
}
```
