### ISSUE TITLE
Unterminate

### ISSUE THREAD

**Issue by noxitechdk** [VertisanPRO/pterodactyl#453]
### Describe the solution you'd like

![image](https://github.com/WemXPro/tracker/assets/118081323/d3d1995a-533f-41f7-b767-e661be487dac)

Do so you can unterminate a server. This will just create the server from new.

**Comment by VanillaChan6571** [comment]
Unterminate is not possible, use suspend for what you need.

**Comment by PadowYT2** [comment]
Use "unsuspend"
