### ISSUE TITLE
Affiliates Earnings are Rounded.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#455]
### Describe the issue

The Affiliates Balance is getting rounded down, Unsure why. Mubeen pls fix thx.

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

-

### Additional Information

Solution:

`app/helpers.php`

`function price(int $price = 0, int $decimal = 2, bool $code = false)` -> `function price($price = 0, int $decimal = 2, bool $code = false)`

**Comment by Mubeen142** [comment]
this was only an issue within the latest dev version. We have fixed the problem
