### ISSUE TITLE
[Critical] Ignore Error 500 from https://flagsapi.com  during Checkout | or that does not effect the checkout function.

### ISSUE THREAD

**Issue by VanillaChan6571** [VertisanPRO/pterodactyl#456]
### Describe the issue

pt-BR seems to be an error 500, and I have currently disable Flags API by renaming it to flagsapi-notworking.com

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

--

### Expected Behaviour

Ignore Error 500 from external errors like flagsapi, something that does not effect the gateway function.

### Additional Information

Switch to more of a local icons base instead of relying on flagsapi or external apis to host simple icons like flags?

**Comment by GIGABAIT93** [comment]
https://github.com/WemXPro/languages
It has been renamed in recent versions. You need to remove pt-BR from the localization directory

**Comment by VanillaChan6571** [comment]
Then this was not properly updated in the dev version.

**Comment by GIGABAIT93** [comment]
the problem is that this localization remained with you from old versions
