### ISSUE TITLE
Make Recaptcha on /auth/register

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#46]
### Resource

Billing

### Describe the issue

![](https://i.imgur.com/uXuu3A9.png)
![](https://cdn.discordapp.com/attachments/910261824455319602/1022496826152202350/unknown.png)
![](https://i.imgur.com/SfZKsoh.png)
![](https://i.imgur.com/iEB87M5.png)
![](https://i.imgur.com/oQeInp4.png)
![](https://i.imgur.com/zedPy8I.png)
![](https://i.imgur.com/2YqnClY.png)
![](https://i.imgur.com/MBIE9cN.png)

### Pterodactyl Panel Version

1.10.1

### Resource Version

2.6.0

### To Reproduce

Create an account

### Expected Behaviour

1: Recaptcha Prevents attacks
2: cloudflare

### Additional Information

**Mod edit: making recaptcha work, is the fix**

**Comment by MyShoesHaveSplinters** [comment]
This is bad, does this effect all the users who owns the billing node?

**Comment by Mubeen142** [comment]
Hi @ZEROPOINTBRUH 

Thanks for the report, we will fix it the following update.

**Comment by ZEROPOINTBRUH** [comment]
# This is still an issue.
