### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by LIADPRODUCTIONS** [VertisanPRO/pterodactyl#460]
### Describe the issue

When i open my website, It doesn't load the CSS, I assume its not anyway because it is all jumbled and all the text is just plain text on a white background.
It sometimes works for the main homepage but it doesn't for the dashboard. The admin panel works just fine.
My website running WemX is [https://acenodes.co.uk/](https://acenodes.co.uk/)

### Product Version

2.1.0

### To Reproduce

I do not know, It happened by itself all of a sudden.

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/83298516/91cc957c-bdeb-4a74-8da0-9776d437f67b)

**Comment by PadowYT2** [comment]
Disable Cloudflare Rocket loader
