### ISSUE TITLE
Setup fee not being added.

### ISSUE THREAD

**Issue by mrayden** [VertisanPRO/pterodactyl#462]
### Describe the issue

When I add a setup fee, and try to purchase it (lets say the setup fee is $1 and the service is $6), it says the price is $6, but I only get charged for $6.

### Product Version

1.4.0

### To Reproduce

Add a setup fee, and purchase or go to the paypal screen where it says the purchase amount or something.

### Expected Behaviour

Setup fee added, checkout $7

**Comment by PadowYT2** [comment]
Unable to reproduce
