### ISSUE TITLE
Email Error with member system

### ISSUE THREAD

**Issue by Coderbot4321** [VertisanPRO/pterodactyl#468]
### Describe the issue

The email a user receives when invites to a server as a member says from WemX instead of my name.

### Product Version

2.0.1

### Pterodactyl Panel Version (if applicable)

NA

### To Reproduce

Add a user to a server via email, then see if email is tagged as in regards from WemX.

### Expected Behaviour

To say:
Regards,
<my company name>

### Screenshots

[Issue.pdf](https://github.com/user-attachments/files/15572511/Issue.pdf)

**Comment by PadowYT2** [comment]
Have you edited the email template?

**Comment by Coderbot4321** [comment]
No, how do I do that?
