### ISSUE TITLE
Server Transfer Dosn't Transfer

### ISSUE THREAD

**Issue by MyShoesHaveSplinters** [VertisanPRO/pterodactyl#47]
### Resource

Billing

### Describe the issue

I ran a few tests. and the server fails to transfer with the billing node on.
It does not do this in the panel, but with billing node it does.

### Pterodactyl Panel Version

latest

### Resource Version

2.5.5

### To Reproduce

1: transfer an active server
2: server begins transfer
3: server stops responding

### Expected Behaviour

Server Transfers
Server Reallocates
Server Transfer Complete

**Comment by Mubeen142** [comment]
Hi,

Billing does not handle server transfers, it's handled by Pterodactyl
