### ISSUE TITLE
"Esential cookies" is not spelled correctly

### ISSUE THREAD

**Issue by purejosh** [VertisanPRO/pterodactyl#473]
### Describe the issue

On the cookies acceptance popup, the word "essential" is spelled incorrectly, as "esential". Please correct spelling. 

### Product Version

2.1.0

### Pterodactyl Panel Version (if applicable)

n/a

### Screenshots

![image](https://github.com/WemXPro/tracker/assets/70633949/72cfb24e-e38b-495a-b39e-2ff7a2dee897)

**Comment by Mubeen142** [comment]
thanks for the report, its has been fixed

**Comment by purejosh** [comment]
I noticed there's a very large amount of spelling mistakes. I may, in the future if I have spare time, submit a PR to correct these mistakes.
