### ISSUE TITLE
Cookie dialog issues

### ISSUE THREAD

**Issue by K4ryuu** [VertisanPRO/pterodactyl#479]
### Describe the issue

The cookie dialog is blocked by default within some browsers (for example Safari and Brave) and you cannot access the website. You see only a tinted windows with the content due to the cookie dialog colors the background, but the dialog itself is blocked by them. This also happens on some mobile browsers. In safari for example you have to click on the url on top and disable the content blockers fully, but some users don't know these.

### Product Version

2.1.0

### To Reproduce

1. Use Safari, Brave or so
2. Open the website in incognito

### Expected Behaviour

To show the dialog or if its blocked let the user access the site without blocked them fully forever.

### Screenshots

![CleanShot 2024-07-01 at 22 26 39@2x](https://github.com/WemXPro/tracker/assets/104531589/368849f8-f588-4b9f-a46e-8bd20d881eba)

**Comment by EWANZO101** [comment]
untrue  this sounds like its a cache issuse or u have a vpn or ad blocker 
![WhatsApp Image 2024-07-01 at 21 37 42_d71ef371](https://github.com/WemXPro/tracker/assets/107235474/de77a420-e542-4cda-8643-b0afc5236495)

**Comment by EWANZO101** [comment]
Your website 

![WhatsApp Image 2024-07-01 at 21 42 32_3e50566d](https://github.com/WemXPro/tracker/assets/107235474/2424b620-fe5e-4423-b698-1f0ec165be95)

**Comment by KinglyMinecon** [comment]
Its the same for me. I use brave

**Comment by KinglyMinecon** [comment]
![Screenshot_20240701-214353_Brave](https://github.com/WemXPro/tracker/assets/88132731/4a36a17a-f9dc-4d45-8068-7c583f8917d3)

**Comment by PadowYT2** [comment]
Known problem, you need to disable some of the protection from Brave

**Comment by KinglyMinecon** [comment]
So your basically saying that its the browsers fault.
No one has this issue with any other website.
It is wemx. Just fix it

**Comment by EWANZO101** [comment]
> So your basically saying that its the browsers fault. No one has this issue with any other website. It is wemx. Just fix it

well to be fair its just brave thats been known to have this issue so really one browser is the problem  

There is 5 other big known browesrs u could use

**Comment by K4ryuu** [comment]
> > So your basically saying that its the browsers fault. No one has this issue with any other website. It is wemx. Just fix it
> 
> well to be fair its just brave thats been known to have this issue so really one browser is the problem

My main issue is in Safari tho. I don't use Brave it was just reported by a user too.
If this is enabled (by default for everyone), then you can't see it.

![CleanShot 2024-07-01 at 22 53 18@2x](https://github.com/WemXPro/tracker/assets/104531589/1c0c169e-3efa-4278-8c4d-324fd5c45e6b)

**Comment by EWANZO101** [comment]
again as i said i use it all the time on Safari so it seems this might be a issue with your settings as Padow said

**Comment by KinglyMinecon** [comment]
The thing is brave is like this.
It is how wemx is made
