### ISSUE TITLE
Socialite bypasses/ignore 2FA

### ISSUE THREAD

**Issue by Jessasaurus** [VertisanPRO/pterodactyl#48]
### Resource

Socialite

### Describe the issue

Socialite seems to bypass/ignore 2FA on accounts with it enabled

### Pterodactyl Panel Version

1.10.1

### Resource Version

1.2.0

### To Reproduce

create account on panel setup/enable 2FA, logout, login to new account using Socialite ignore 2FA

### Expected Behaviour

2FA that's enabled on accounts should also show up when login in

**Comment by hwalker928** [comment]
This is probably expected behaviour, as I'm guessing that 2FA would be handled by the provider rather than Pterodactyl.

**Comment by PadowYT2** [comment]
Hey, this won't be done as this is super hard to make, would require a bunch of redirects, as to get the 2fa page, you have to post a request with tokens, which iirc can't be done in our situation
