### ISSUE TITLE
Integration with google translate

### ISSUE THREAD

**Issue by joti-prime** [VertisanPRO/pterodactyl#482]
### Describe the solution you'd like

Integration of Google Translate (javascript) to be used for translations, this way the entire visual part would be translated in any language with just a few clicks and only things like emails or things that are not visualized within wemx would have to be translated or maybe can be also integrated with google translate.

**Comment by joti-prime** [comment]
https://stackoverflow.com/questions/12243818/adding-google-translate-to-a-web-site
https://cloud.google.com/translate/docs/reference/rest
https://gist.github.com/JT5D/a2fdfefa80124a06f5a9#file-gistfile1-txt

**Comment by PadowYT2** [comment]
Looks useless to me, as we have translations themselfs, and if you need google translate, just use the built-in browser feature (if exists) or use https://translate.google.com/?op=websites
