### ISSUE TITLE
Request Deletion of account

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#49]
### Resource

Billing

### Is your feature request related to a problem? Please describe

If the user wants to request deletion of the account, we should make it an option where they can request accounts to be deleted.

### Describe the solution you'd like

Request Account Deletion. 
An email will be sent out to the user that the account was requested deletion, giving them 15 days to log back in or the account is deleted.

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
