### ISSUE TITLE
Improvement of the built-in server control panel

### ISSUE THREAD

**Issue by PM-KIRILL** [VertisanPRO/pterodactyl#498]
### Describe the solution you'd like

Hello, I would like the built-in server control panel to be improved so that it is more functional and can fully replace Pterodactyl.

### Describe alternatives you've considered

The built-in panel has too modest functionality and cannot fully replace the Pterodactyl panel.

**Comment by PadowYT2** [comment]
You need to actually say what to improve, we can't just improve something we don't know what to improve
