### ISSUE TITLE
Umod Plugin for rust, Steam Workshop Plugin for most steam games compatable [Willing to help out in this project]

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#50]
### Resource

Plugins

### Is your feature request related to a problem? Please describe

Some users with, Rust servers, Garry's Mod Servers, Unturned Servers, and many more steam games would usually have either a workshop or Third Party Mod Support.

### Describe the solution you'd like

I'm willing to help and locate where to get mods for the games and locate the folders required for the workshop mods/Trusted third party mods.

Create two additional sections for Workshop mods [Lots Steam Games], Umod [Rust], Sourcemod [Team Fortress 2, Portal 2, Left For Dead 1/2].

**Comment by PadowYT2** [comment]
Plugins are not 1.7+, but will have a nice feature in Billing

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
