### ISSUE TITLE
New Feature for Lang System

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#503]
### Describe the solution you'd like

How about an option that allows you to choose which languages a user can switch between, i.e. that can be set in the lunage select dropdown

**Comment by PadowYT2** [comment]
Just delete the languages you don't need

**Comment by Partymann2000** [comment]
but it would be more user friendly for people who are not familiar with the material

do you decide if it goes in or is it discussed, just out of interest
