### ISSUE TITLE
ipqualityscore.com and detecting abusive accounts

### ISSUE THREAD

**Issue by IkdanYT** [VertisanPRO/pterodactyl#505]
### Describe the solution you'd like

Add duplicate account detection and the ability to set them up automatically on manual verification, exactly the same thing to do with VPNs.
You can use ipqualityscore functions.
Configuration through a separate category, can be made a module.
In the settings the possibility to configure all parameters with api key.

**Comment by PadowYT2** [comment]
Duplicate of #265
