### ISSUE TITLE
Update all resources to new version

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#51]
### Resource

All of them

### Is your feature request related to a problem? Please describe

Everything is outdated, its time for an update.

### Describe the solution you'd like

Welp, seems like pterodactyl did it again, you guys know what todo lmao.

### Describe alternatives you've considered

An older version of everything

### Additional context

![](https://i.imgur.com/7AyPSxA.png)

**Comment by AuroraRpg** [comment]
babe wake up, new pterodactyl just dropped

**Comment by moosedoggy** [comment]
Wenimechainthesama
Tumajarbisaun
Wifenloof
Astheleafeturnbraun

**Comment by sev-ofc** [comment]
damn daniel

**Comment by Zaxbys** [comment]
*in a mario voice* here we go!
