### ISSUE TITLE
Change what one credit/1$ is worth for your balance 

### ISSUE THREAD

**Issue by AydenC77** [VertisanPRO/pterodactyl#513]
### ability to change what a dollar in your balance is worth

For example i would set 1 credit to be equal to 5$ in money so you would buy 1 credit for 5 dollars and this allows store owners to create a credit system to give rewards for taking a survey or something else with out affecting the currency price of the item for example people could have 400 credits In their balance but the currency price for a item is 5$ but it would take 300 credits to get the product with their balance 

### Additional context

I think you guys should add this as it allows shop owners to create a reward system for people taking surveys voting for the website or leaving reviews something or in my use case allowing people to do tasks in game to get credits towards my site

**Comment by purejosh** [comment]
I'm pretty sure it's against the ToS for almost every popular game to earn real world monetization in game. You'd be breaking ToS if you allowed in game actions to provide a real world monetary benefit. 

Additionally credit systems are far too confusing by themselves. Add credits and money to the same system, and you've got a mess. Just my two cents.

**Comment by PadowYT2** [comment]
We won't be adding a credit system alongside a balance system. That's kinda useless and illegal in some cases (I think)
