### ISSUE TITLE
Configurable options - Default to first option, not last, in dropdown

### ISSUE THREAD

**Issue by purejosh** [VertisanPRO/pterodactyl#515]
### Describe the solution you'd like

In the dropdown options for a configured feature, it defaults to the last value in the list. This is generally the most expensive option. Please consider changing the default value to the first option in the list. 

Here you can see that the page loaded with 6 threads selected, but in general, lists should always start with the first option, not the last. 
![image](https://github.com/user-attachments/assets/d72b63e8-70a3-4f33-9b68-46d5adf98ca4)

**Comment by Mubeen142** [comment]
thanks for the report. I have updated it to use the first value
