### ISSUE TITLE
Integrating Services

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#52]
### Resource

Billing

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

We would like to integrate the following services

## Integrations
Trust Pilot: Allow users to see reviews on the portal page.
Google Analytics: Tracking User Statistics.
Google AdWord: Placing Ads on the portal page and plans page.
![](https://i.imgur.com/fN7NQ7Y.png)
- Idea I've got from some other software

## Progressive Web App
- Allow users to download an app from the website without downloading the app from the AppStore or consuming space from downloading a whole new client.
-  This means that users have an 'Add to Homescreen' option for your site

## Anti Temp Mail 
https://github.com/FGRibreau/mailchecker/blob/master/list.txt

## BanIP
Ban User IPs

## OAuth Login
Allow users to login/signup using google, github, facebook, Discord

## Pwned Password Api
Allow users to see if there password is on the database of breached passwords or account has been breached on haveibeenpwned's API

### Describe alternatives you've considered

no

### Additional context

no

**Comment by ZEROPOINTBRUH** [comment]
# SEO
Allows users to setup there own SEO in the meantime
- This is an example from a third party forum software
![](https://i.imgur.com/WXzchqR.png)

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
