### ISSUE TITLE
Clicking on empty Users at Groups causes server error

### ISSUE THREAD

**Issue by K4ryuu** [VertisanPRO/pterodactyl#524]
### Describe the issue

When you create a new group at Groups, and it has no users in it, but you click on users, you get this error:
![CleanShot 2024-10-06 at 00 09 30@2x](https://github.com/user-attachments/assets/6790f2cd-c9bb-4687-8166-e89f851bf33b)

EDIT: It happens aswell if Users added to the group.

### Product Version

2.2.0

**Comment by Mubeen142** [comment]
Thanks for your report

The issue was happening in all groups even in groups that had users. It was a simple syntax issue. I have fixed it for next update
