### ISSUE TITLE
Ban punishment, causing site wide account being suspended

### ISSUE THREAD

**Issue by Domatron** [VertisanPRO/pterodactyl#526]
### Describe the issue

Any banned user will cause the site to suspend every user
IPBan does **not** cause this issue, just ban
Example:
![image](https://github.com/user-attachments/assets/501a99b1-dad9-473d-85f3-c61c735d05df)

### Product Version

2.2.0

### To Reproduce

Ban a user on the wemx admin page
Refresh the page to get an error
Example:
![image](https://github.com/user-attachments/assets/66ee23d0-83c4-434a-9792-bb22408759db)

### Expected Behaviour

User being banned only

**Comment by PadowYT2** [comment]
If you have a Cloudflare IP on your account (in devices), then that's the problem. You need to remove all of them

**Comment by Mubeen142** [comment]
Thank you for reporting this bug! We have fixed it for next update
