### ISSUE TITLE
Automatic renewal

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#528]
### Describe the issue

It would be good if you could switch the automatic renewals off and on separately for each package, e.g. if you take a free server and don't have it forever

### Product Version

2.2.0

### To Reproduce

It would be good if you could switch the automatic renewals off and on separately for each package, e.g. if you take a free server and don't have it forever

**Comment by Mubeen142** [comment]
Thank you for reporting this issue. I have added option to disable auto balance renewal per package
![Screenshot 2024-10-13 at 01 25 34](https://github.com/user-attachments/assets/34d1d59b-d36c-4490-b585-db043d620ef7)
