### ISSUE TITLE
Billing admin users tab working slow/Add pages on the tab.

### ISSUE THREAD

**Issue by Huguitis** [VertisanPRO/pterodactyl#53]
### Resource

Billing

### Describe the issue

When there is a large number of registered users by going to the users section in the billing admin tab, the page works with a los of lag (especially on mobile devices)

### Pterodactyl Panel Version

1.10.1

### Resource Version

2.5.0

### To Reproduce

1. Have a panel with a lot of users. (Like 700)
2. Go to the admin tab.
3. Go to the users billing tab.

### Expected Behaviour

That the page works without lag and correctly.
My feature request would be that there are pages in this section.

**Comment by ZEROPOINTBRUH** [comment]
isn't it 2.5.5, if not, your a version behind

**Comment by ZEROPOINTBRUH** [comment]
> ### Resource
> Billing
> 
> ### Describe the issue
> When there is a large number of registered users by going to the users section in the billing admin tab, the page works with a los of lag (especially on mobile devices)
> 
> ### Pterodactyl Panel Version
> 1.10.1
> 
> ### Resource Version
> 2.5.0
> 
> ### To Reproduce
> 1. Have a panel with a lot of users. (Like 700)
> 2. Go to the admin tab.
> 3. Go to the users billing tab.
> 
> ### Expected Behaviour
> That the page works without lag and correctly. My feature request would be that there are pages in this section.
> 
> ### Screenshots
> _No response_
> 
> ### Additional Information
> _No response_

but yea, this has been confirmed to happen on the current version of the billing node.

**Comment by Huguitis** [comment]
> isn't it 2.5.5, if not, your a version behind

Right, sorry.

**Comment by Mubeen142** [comment]
Hey @Huguitis 

This issue was fixed in the next update :) I added server side pagination.

So now, the user will be loaded 20 times each request and you can change through pages
