### ISSUE TITLE
Settings -> Configuration -> Registration -> Default Avatar input set to URL

### ISSUE THREAD

**Issue by ghost** [VertisanPRO/pterodactyl#536]
### Describe the issue

This shouldn't be set to URL as sometime you can use a local path to define the default avatar image.

![image](https://github.com/user-attachments/assets/d92e222f-8981-4910-bcfe-78108520fc92)
 Only way around it is if you edit the HTML using inspect and put it as a text input field and then hit submit. That works to get around it.

### Product Version

I don't know how to find the version

### Pterodactyl Panel Version (if applicable)

1.11.10

### To Reproduce

Try and submit the form with a local string for the image

**Comment by PadowYT2** [comment]
You should input `https://your.domain/images/logo.png`

**Comment by PadowYT2** [comment]
o

**Comment by ghost** [comment]
> You should input `https://your.domain/images/logo.png`

Why would I want to use a direct link when i can load it locally? That makes no sense. You should be able to do both.

**Comment by PadowYT2** [comment]
> i can load it locally

That's not how it works, if you could use local files, then the web would be in disaster. If you for example put `/abc`, then it will become the current domain (and subdomain if present) + `/abc`

**Comment by ghost** [comment]
Yea, but laravel has a wonderful helper function called asset() that will resolve that into the correct domain? Why isn't a native Laravel helper function being used in this instance?

If i have an image in my root web / public folder in /public/images/whatever.png.... I should be calling it in my blade as `asset("images/whatever.png")`. Why would I want to make a call OUTSIDE the local network to basically my own server, making a huge loop, when I can just serve the image out of my public folder? I mean its still coming out of the same server? I don't understand.

If the default text is of "local file inclusion" by it being `/images/logo.png`, then I should be able to put `/images/mylogo.png`, otherwise, the default should be populated using the ENV variable APP_URL, and then appending on the /images/logo.png as this would make more sense UX wise as its local file inclusion in the example/default and external file linking using a URL in reality. This is very confusing to the end user.

IMO to reduce user confusion and enhance UX either the default value of the field need to be accurately displayed as a URL instead of local file inclusion, OR the field needs to just be set to text, as setting this to text in NO WAY shape or form breaks anything for anyone as Wemx literally just dumps the value into the image src parameter. So local either way, both methods work.

**Comment by shanecaf** [comment]
I think really both URLs and Local paths should be supported for this. Or just provide an option to upload the image to the server itself. So probably having it as just text would be better.

**Comment by shanecaf** [comment]
> > i can load it locally
> 
> That's not how it works, if you could use local files, then the web would be in disaster. If you for example put `/abc`, then it will become the current domain (and subdomain if present) + `/abc`

Typically it's recommended to always host the resources locally within the server, rather than relying on a third party service to host it.

**Comment by ghost** [comment]
> > > i can load it locally
> > 
> > 
> > That's not how it works, if you could use local files, then the web would be in disaster. If you for example put `/abc`, then it will become the current domain (and subdomain if present) + `/abc`
> 
> Typically it's recommended to always host the resources locally within the server, rather than relying on a third party service to host it.

Exactly. Like in laravel you're supposed to store this shit in the storage directory. and then call it using the asset helper or some other function that i've forgotten of the top of my head. But yea, the input tags type should be text and not URL. Forcing me to have it as URL means that i can't just click save on my installation. I have to manually edit the html using the inspector.

Which oh yea, by the way, the default value upon installing wemx doesn't even allow you to save because its defaulted to a local instance of a file. Lol
