### ISSUE TITLE
Plans And Order Issue

### ISSUE THREAD

**Issue by bogeybro0077** [VertisanPRO/pterodactyl#57]
### Resource

Billing

### Describe the issue

When you delete a plan any order with that plan can no long be accessed through the managed button

### Pterodactyl Panel Version

1.4.0

### Resource Version

3.0.0

### To Reproduce

1. Make a plan
2. Create an order under the plan
3. Delete the plan
4. Try to manage the order

### Expected Behaviour

The ability to still go in and mark it as paid or somthing

**Comment by PadowYT2** [comment]
Not an issue, you've deleted the plan, how are you supposed to manage the frontend plan. It is like somehow deleting a Node and now you can't edit the servers (imagine if it was like that)
