### ISSUE TITLE
More Configuration

### ISSUE THREAD

**Issue by bogeybro0077** [VertisanPRO/pterodactyl#60]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Cant configure messages that are on the /portal page and other pages

### Describe the solution you'd like

The ability to configure different parts of the portal page, like the features list, etc

**Comment by PadowYT2** [comment]
This is not going to be a feature. And there are a lot of changes to talk about: CSS, language, placement. So looking into the files is the choice
