### ISSUE TITLE
Legal problem in Germany (DSGVO)

### ISSUE THREAD

**Issue by Partymann2000** [VertisanPRO/pterodactyl#61]
### Resource

Billing

### Describe the issue

Hey, I just discovered a problem that I think should be patched, as this can result in penalties in Germany.
What is the problem exactly? 
The problem is with the dynamic integration of the Google fonts, because there the following things are forwarded to Google that fall under the German data protection and the users do not realize that there fonts are loaded dynamically by Google.
Here are the problems (what is transmitted to Google)
- IP addresses
- Which browser is used
- Which website is visited
- Which operating system is used
- Language settings of the browser
- Screen resolution
It would be great if you could have the fonts statically, i.e. locally.

### Pterodactyl Panel Version

All

### Resource Version

All

### To Reproduce

Nothing Google Fonts (when i go of this website ita load automaticly the font)

### Expected Behaviour

That it is saved and retrieved locally and not dynamically via api/online query

### Additional Information

It must be stored for the German market local

**Comment by PadowYT2** [comment]
Won't be done, because default Pterodactyl also uses google for fonts
