### ISSUE TITLE
One time payment services

### ISSUE THREAD

**Issue by MrFoxyOfficial** [VertisanPRO/pterodactyl#62]
### Resource

Billing

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Module called Services

### Additional context

Instead of having a plan, that would automatically create a new server, it could just be a service listing, for example, a Setup fee. This would indicate, that the user would need help installing a bot or setting the bot up, without the system creating a new server.

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
