### ISSUE TITLE
Theme Overlaps Settings

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#63]
### Resource

Billing

### Describe the issue

![](https://i.imgur.com/QXP7Ka6.png)

### Pterodactyl Panel Version

1.10.4

### Resource Version

3

### To Reproduce

open settings in a portrait window

### Expected Behaviour

no overlapping

**Comment by ZEROPOINTBRUH** [comment]
![](https://i.imgur.com/a7OtjJg.png)

**Comment by PadowYT2** [comment]
Cannot reproduce on Billing, probably same with Carbon
