### ISSUE TITLE
Impersonate User Feature Transfers you to /portal without access

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#64]
### Resource

Billing

### Describe the issue

Impersonate user transfers you to the portal page without access

### Pterodactyl Panel Version

1.10.4

### Resource Version

3

### To Reproduce

Login
Admin Settings
Billing
Billing Users
Impersonate User
/portal

### Expected Behaviour

Button Functions as intended

**Comment by MrFoxyOfficial** [comment]
and what do you think it was supposed to do? You're impersonating that specific user, with permissions that they have.

**Comment by ZEROPOINTBRUH** [comment]
wrong, you are logged out of the account your signed onto. taking you back to the /portal paged logged out.

**Comment by PadowYT2** [comment]
It redirects fine for me, to `/account`

**Comment by 0xBitMC** [comment]
This issue still persist. 

I am using Pterodactyl 1.11.2 and Billing Version 3.3.0

One I click the "login as user" button which redirects me to `href="https://panel.domain.net/billing/admin/impersonate/4"`, this forwards me back to `https://panel.domain.net/portal` and does not impersonate. However in the recent events section, it shows show an event for `admin:impersonate:user` firing. 

I initially thought this was a cookie error, however this was not the case after trying multiple browsers and incognito window.

Please investigate this issue further, thank you.

**Comment by PadowYT2** [comment]
> This issue still persist. 
> 
> I am using Pterodactyl 1.11.2 and Billing Version 3.3.0
> 
> One I click the "login as user" button which redirects me to `href="https://panel.domain.net/billing/admin/impersonate/4"`, this forwards me back to `https://panel.domain.net/portal` and does not impersonate. However in the recent events section, it shows show an event for `admin:impersonate:user` firing. 
> 
> I initially thought this was a cookie error, however this was not the case after trying multiple browsers and incognito window.
> 
> Please investigate this issue further, thank you.

Hey there, I still don't have the issue, can you send me in dms your panel url and create me an admin account

**Comment by VanillaChan6571** [comment]
Bump as confirmed issue, not sure why it’s marked as invalid.

**Comment by PadowYT2** [comment]
Hey could you dm me

**Comment by VanillaChan6571** [comment]
After Testing with PadowYT2 seems like a ($id is not defined)/Caching Issue with ID's so only working bypass to get this to work properly..

1. before hitting the yellow button that says "login as user". Clear Cache by pressing **Control + F5**, _you should be still logged in as the admin and stayed on the page as it reloaded._ and then "login as user". 
2. The redirect page will reload about 2-3 times then your into that users account that you attempted to login. 

Before that it would just take you back to the portal page and logged out. So that's the only bypass solution I have and works 95% of the time.

**Comment by ZEROPOINTBRUH** [comment]
Bump: Issue is valid, another person I've been helping setup there billing module for the first time had the same issue on the latest version of the billing module. 

Impersonate user logs out the current user taking them back to the portal page.
