### ISSUE TITLE
White Background /auth/register

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#65]
### Resource

Billing

### Describe the issue

![](https://i.imgur.com/IUv8wYM.png)

### Pterodactyl Panel Version

1.10.4

### Resource Version

3

### To Reproduce

goto /auth/register
![](https://i.imgur.com/IUv8wYM.png)

### Expected Behaviour

Background change

**Comment by PadowYT2** [comment]
This is known, fix: https://canary.discord.com/channels/760945720470667294/910261824455319602/1004998486158229534
