### ISSUE TITLE
Subtext is white in Error Pages

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#66]
### Resource

Billing

### Describe the issue

![](https://i.imgur.com/wX4pyFE.png)
![](https://i.imgur.com/rEsilbT.png)

### Pterodactyl Panel Version

1.10.4

### Resource Version

3

### To Reproduce

find an error page
Text blended in with page

### Expected Behaviour

Devs slightly change the css

**Comment by PadowYT2** [comment]
I believe this was fixed, if not, @ me so I can reopen the issue
