### ISSUE TITLE
Server Subuser exsists issue

### ISSUE THREAD

**Issue by ZEROPOINTBRUH** [VertisanPRO/pterodactyl#67]
### Resource

Billing

### Describe the issue

![](https://i.imgur.com/jvLO8Wd.png)

### Pterodactyl Panel Version

1.10.4

### Resource Version

3

### To Reproduce

![](https://i.imgur.com/jvLO8Wd.png)

### Expected Behaviour

Signup works

**Comment by PadowYT2** [comment]
This is known, go to the support channel
