### ISSUE TITLE
Let us edit the package more

### ISSUE THREAD

**Issue by Davidbp99** [VertisanPRO/pterodactyl#7]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Right now we must remake the package fully to change 1 thing. This takes up time and bit of a pain.

### Describe the solution you'd like

Let us edit the package ram, cpu %, harddrive space, backup, database etc

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
