### ISSUE TITLE
More control

### ISSUE THREAD

**Issue by DawgTwist** [VertisanPRO/pterodactyl#71]
Hello I think you should give us more control in the next update like let us change more things in plans area and when about to buy make so when you click add to cart another page pops up and you can add custom things to it like dedicated ip and it costs $2 extra a month or like add more storage just things like that also it would be cool if you made Unix compatible with the billing module also let us be able to customize the portal page and the panel page even more and make it easier then having to open in a file manager and kinda make it similar to whmcs thank you.

**Comment by PadowYT2** [comment]
> let us change more things in plans area
#7
> when about to buy make so when you click add to cart another page pops up and you can add custom things to it like dedicated ip and it costs $2 extra a month or like add more storage just things like that
#6
> also it would be cool if you made Unix compatible with the billing module
Will be made, but in totally future, no issue needed, as Unix is not the only theme
> let us be able to customize the portal page and the panel page
#60
> make it easier then *(what)* having to open in a file manager
What do you mean easier?
> kinda make it similar to whmcs
Making what similar to WHCMS?

## Overall
Please, don't put everything in the title and make everything properly aligned, commas, new lines. Also divide category of the suggestions into another issues
