### ISSUE TITLE
Custom domains/subdomains and SSL for web hosting

### ISSUE THREAD

**Issue by BethDevJS** [VertisanPRO/pterodactyl#72]
Resource

Billing

Is your feature request related to a problem? Please describe

At the moment for the web hosting egg to view the website you must visit the domain + port which can be extremely unattractive to users who are wanting to have full web server control and aren’t wanting all users to add a port to the end: example.com looks better than example.com:23856

Describe the solution you'd like

To be able to have subdomain support for nginx web servers and support SSL certificates

Describe alternatives you've considered

It seems at the moment the egg doesn’t have much use unless you don’t already have an existing web server and are happy to giveaway port 80 to 1 user and not be able to do it for anybody else 

Additional context

It would also be best to add support for SSL certificates as it goes back to the thing before about user trust, regardless of the websites content, if someone sees that infamous “not secure” they’re going to be extremely cautious of even the most secure websites in the world

**Comment by PadowYT2** [comment]
Forgot to respond, anyways this can't be possible as it would require creating files on the root host. You could currently use something like NGINX Proxy Manager. Also you didn't use the template for the issue
