### ISSUE TITLE
Reoccuring server renewal affiliate rewards

### ISSUE THREAD

**Issue by BethDevJS** [VertisanPRO/pterodactyl#73]
### Resource

Billing

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

At current affiliates are only able to get rewards for the first month of their users purchases however a very attractive feature from hosts is a reoccuring affiliate reward so that they are getting the reward from each month their users are paying for a server

### Describe alternatives you've considered

The only alternative is to build your own solution to watch for server renewals and then add the correct amount to the affiliates balance

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
