### ISSUE TITLE
Undefined variable $plan

### ISSUE THREAD

**Issue by BethDevJS** [VertisanPRO/pterodactyl#74]
### Resource

Billing

### Describe the issue

When having a fresh install of the billing module I am greeting with this error everytime I place an order, with an empty or full cart, the only way to stop it and allow people to place orders is to remove the $plan from the source code

### Pterodactyl Panel Version

1.11.3

### Resource Version

3.4.0

### To Reproduce

1, Install the billing module
2. Go to cart, you don't have to have anything in it
3. Place the order
4. Error

### Expected Behaviour

The site should say nothing in the cart or process the order but gets stuck on a 500 error for this $plan being undefined 

### Screenshots

![image](https://user-images.githubusercontent.com/70341936/224575737-d33d483e-a728-4790-ab7c-d81da137fab1.png)

**Comment by PadowYT2** [comment]
SMTP is not setup
