### ISSUE TITLE
Class "PteroApi" not found

### ISSUE THREAD

**Issue by BethDevJS** [VertisanPRO/pterodactyl#75]
### Resource

Billing

### Describe the issue

After installing the panel I am getting a Class "PteroApi" not found error after placing an order, I have tried reinstalling the module but it doesn't make much difference

### Pterodactyl Panel Version

1.11.3

### Resource Version

3.4.0

### To Reproduce

1, Install the billing module
2. Go to cart, you don't have to have anything in it
3. Place the order
4. Error

### Expected Behaviour

The site should say nothing in the cart or process the order but gets stuck on a 500 error for this $plan being undefined

### Screenshots

![image](https://user-images.githubusercontent.com/70341936/224576126-c127e1b0-6a1a-46a4-a61c-c10d18a40d25.png)

**Comment by PadowYT2** [comment]
Seems that you somehow deleted it, reinstall Billing
