### ISSUE TITLE
Plans dropdown

### ISSUE THREAD

**Issue by uplandstatue** [VertisanPRO/pterodactyl#77]
### Resource

Billing

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

In many cases we will over multiple plans per game, in our case for example we have 6 minecraft plans that start as a forge edition and that is for the one month only, if we wanted to add a 3 month and 6 month version of each plan it would grow rapidly and get tricky to manage. Instead if there was an option (everyone may not need this, so enabling it should be optional and the extended length times can be configured by the billing panel admin) to add a drop down or other filter selection at the top of the plans page for duration and an additional configuration section under the plans in the billing admin section that is like discount for extended period 1 and extend period 2 so that we can set a discount based on the length of the plan.

### Describe alternatives you've considered

I'm sure there are multiple ways to implement something similar and knowing your code means you should surely know the better way to implement a configuration like this, just to me cluttering the plans with duplicates based on time is not very helpful.

### Additional context

![featurerequest1](https://user-images.githubusercontent.com/51497978/225337169-e2889f6e-f6e4-4f29-a82f-d18cf4e8c752.png)

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro/
