### ISSUE TITLE
incorrect redirect in page preview button

### ISSUE THREAD

**Issue by itzJOHv** [VertisanPRO/pterodactyl#81]
### Resource

Billing

### Describe the issue

the ![image](https://user-images.githubusercontent.com/68508885/230435327-1f68d527-7381-4748-bc64-6350758385c3.png) button redirects to `/page/<URL>` instead of `<URL>`

### Pterodactyl Panel Version

1.11.3

### Resource Version

3.4.0

### To Reproduce

1. go to pages section of billing settings
2. create a redirect page
3. click on the ![image](https://user-images.githubusercontent.com/68508885/230435254-b38fb7e4-59cc-48ae-b506-930ba53caf87.png) button

### Expected Behaviour

i get redirected to the set url

### Screenshots

![image](https://user-images.githubusercontent.com/68508885/230435644-d7032965-eece-452c-8899-73137ba8df3e.png)

**Comment by TiranexDev** [comment]
согласен

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro
