### ISSUE TITLE
(UNIX) [Suggestion] Redesign / Fix of alerts

### ISSUE THREAD

**Issue by DEPSTRCZ** [VertisanPRO/pterodactyl#82]
### Resource

Unix

### Is your feature request related to a problem? Please describe

I think the Alerts in Unix look terrible. The do not correspond with the theme. And they can cause issues when incorrectly configured. (Text not seen etc..)

### Describe the solution you'd like

I would like some kind of redesign.. More simplier and modern so it will fill in with the theme. 
Example: 
![image](https://user-images.githubusercontent.com/77269898/233088700-484e37ba-f80e-49ab-bd0f-a5ac35d47763.png)

To avoid incorrect setting / wrong color combination (Causing the text to be invisible)
I would suggest to keep the text white. And the Title bold.
I would also suggest to make an functionality that if the user picks a white Alert color white to set the text opposite color (Black) so it would be seen.

**Comment by PadowYT2** [comment]
#56
