### ISSUE TITLE
Admin Panel Plans List

### ISSUE THREAD

**Issue by uplandstatue** [VertisanPRO/pterodactyl#83]
### Resource

Billing

### Is your feature request related to a problem? Please describe

Not quite. Just an inconvenience.

### Describe the solution you'd like

Currently the only way to see the number of cores and memory assigned to a plan is to check the portal which only shows memory or to check the database with a manual query. It would be nice if there was a way to see that in a column on the Plans page of the billing admin.

### Describe alternatives you've considered

Scripting custom maraidb queries on the panel via ssh.

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro
