### ISSUE TITLE
Discord account creation

### ISSUE THREAD

**Issue by niterfjord** [VertisanPRO/pterodactyl#90]
### Resource

Billing

### Describe the issue

When an account is automatically created using the Discord module, the user cannot turn on 2FA because the password would be incorrect. Logging in via SFTP does not work either.

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.2.0

**Comment by VanillaChan6571** [comment]
Not a bug, simply have the user reset his password. The bug you posted is invalid.
