### ISSUE TITLE
Round Prices when Discount is Applied

### ISSUE THREAD

**Issue by JonBirdd** [VertisanPRO/pterodactyl#92]
### Resource

Billing

### Describe the solution you'd like

For example, when you discount 15% of 15.99 it shows "13.5915"
would be ideal to show 13.59 and no trailing numbers

### Describe alternatives you've considered

`resources/views/templates/Carbon/billing/plans.blade.php` @ `line 49`
Change
`@endif{{ $plan->price()['price'] }} /`
to
`@endif{{ round($plan->price()['price'], 2) }} /`

`resources/views/templates/Carbon/portal/includes/sections/game_plans.blade.php` @ `line 33`
Change
`{{ $plan->price - ($plan->price * $plan->discount) / 100 }}`
to
`{{ round(($plan->price - ($plan->price * $plan->discount) / 100), 2) }}`

**Comment by PadowYT2** [comment]
Closed due to WemX Pro being out - https://wemx.pro
