### ISSUE TITLE
Automatic setup of additional ports

### ISSUE THREAD

**Issue by LeanoJ** [VertisanPRO/pterodactyl#98]
### Resource

WemX Pro

### Describe the solution you'd like

Already the Billing Module v2 had the feature which created additional ports. If the Egg contained certain variables (e.g. RCON_PORT) an additional port was created and set directly.

If necessary in the admin area even a separate place where all checked variables can be listed. 

At that time I had adapted this to my needs. I had sent the code to Gigabait and Mubeen via dm.

**Comment by PadowYT2** [comment]
This has been added in v1.4.0
