### ISSUE TITLE
Package price and custom renewal price

### ISSUE THREAD

**Issue by redbaron2k7** [VertisanPRO/pterodactyl#99]
### Resource

WemX Pro

### Describe the issue

On the /store/category page, the text above the package price is displayed incorrectly in the image below. I've set the package price to 4, and the renewal price is set to 5.99, but the text displays both prices as the original package price; the second price in the text also has an extra space between the $ and the 4.

![image](https://github.com/VertisanPRO/pterodactyl/assets/76609332/3b439f9b-217a-41d0-ad8c-30c0843dcefe)

### Pterodactyl Panel Version

1.11.3

### Resource Version

1.1.0

**Comment by Mubeen142** [comment]
Thanks for reporting the issue, it has been fixed in the latest update.
